-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color13 = '#0d1017'
local Color12 = '#bfbdb6'
local Color7 = '#1ABC9C'
local Color8 = '#82AAFF'
local Color5 = '#9D7CD8'
local Color2 = '#95E6CB'
local Color0 = '#646b73'
local Color15 = '#2a0e1e'
local Color10 = '#565b66'
local Color3 = '#D2A6FF'
local Color1 = '#AAD94C'
local Color4 = '#BFBDB6'
local Color11 = '#0b0e14'
local Color16 = '#133a52'
local Color6 = '#7DCFFF'
local Color17 = '#464b56'
local Color14 = '#0b2d28'
local Color9 = '#D95757'

highlight('Comment', nil, Color0, 'italic')
highlight('String', nil, Color1, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Number', nil, Color3, nil)
highlight('Identifier', nil, Color4, nil)
highlight('Type', nil, Color5, 'italic')
highlight('Keyword', nil, Color6, nil)
highlight('Operator', nil, Color7, nil)
highlight('Function', nil, Color8, nil)
highlight('Error', nil, Color9, nil)
highlight('StatusLine', Color10, Color11, nil)
highlight('WildMenu', Color13, Color12, nil)
highlight('Pmenu', Color13, Color12, nil)
highlight('PmenuSel', Color12, Color13, nil)
highlight('PmenuThumb', Color13, Color12, nil)
highlight('DiffAdd', Color14, nil, nil)
highlight('DiffDelete', Color15, nil, nil)
highlight('Normal', Color13, Color12, nil)
highlight('Visual', Color16, nil, nil)
highlight('CursorLine', Color16, nil, nil)
highlight('ColorColumn', Color16, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color17, nil)
highlight('TabLine', Color11, Color10, nil)
highlight('TabLineSel', Color12, Color13, nil)
highlight('TabLineFill', Color11, Color10, nil)
highlight('TSPunctDelimiter', nil, Color12, nil)

link('TSConstant', 'Constant')
link('TSFloat', 'Number')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSConditional', 'Conditional')
link('NonText', 'Comment')
link('TSType', 'Type')
link('TSNamespace', 'TSType')
link('TSFunction', 'Function')
link('TSLabel', 'Type')
link('TSString', 'String')
link('TSTag', 'MyTag')
link('Conditional', 'Operator')
link('Operator', 'Keyword')
link('TSNumber', 'Number')
link('TSTagDelimiter', 'Type')
link('TSKeyword', 'Keyword')
link('TSComment', 'Comment')
link('TSPunctBracket', 'MyTag')
link('TSParameter', 'Constant')
link('Repeat', 'Conditional')
link('TelescopeNormal', 'Normal')
link('Folded', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSProperty', 'TSField')
link('TSOperator', 'Operator')
link('TSFuncMacro', 'Macro')
link('Whitespace', 'Comment')
link('CursorLineNr', 'Identifier')
link('Macro', 'Function')
link('TSField', 'Constant')
link('TSRepeat', 'Repeat')
