-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "gamuto"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#0e1118", fg = "#cbd5e8", nocombine = true, sp = "#bfbdb6", underdouble = true })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#0e1118", fg = "#cbd5e8", nocombine = true, sp = "#bfbdb6", underline = true })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.escape", { link = "@string.special" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@variable", { fg = "#d1d4e0" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { ctermfg = 10, fg = "#9aebac" })
hi(0, "BufferLineBackground", { bg = "#0e1116", fg = "#c5d7eb" })
hi(0, "BufferLineBuffer", { bg = "#0e1116", fg = "#c5d7eb" })
hi(0, "BufferLineBufferSelected", { bg = "#0e1118", bold = true, fg = "#dbd5bf", italic = true })
hi(0, "BufferLineBufferVisible", { bg = "#0e1118", fg = "#c5d7eb" })
hi(0, "BufferLineCloseButton", { bg = "#0e1116", fg = "#c5d7eb" })
hi(0, "BufferLineCloseButtonSelected", { bg = "#0e1118", fg = "#dbd5bf" })
hi(0, "BufferLineCloseButtonVisible", { bg = "#0e1118", fg = "#c5d7eb" })
hi(0, "BufferLineDiagnostic", { bg = "#0e1116", fg = "#c8d6e7" })
hi(0, "BufferLineDiagnosticSelected", { bg = "#0e1118", bold = true, fg = "#dbd4c3", italic = true })
hi(0, "BufferLineDiagnosticVisible", { bg = "#0e1118", fg = "#c8d6e7" })
hi(0, "BufferLineDuplicate", { bg = "#0e1116", fg = "#c5d6ec", italic = true })
hi(0, "BufferLineDuplicateSelected", { bg = "#0e1118", fg = "#c5d6ec", italic = true })
hi(0, "BufferLineDuplicateVisible", { bg = "#0e1118", fg = "#c5d6ec", italic = true })
hi(0, "BufferLineError", { bg = "#0e1116", fg = "#c5d7eb", sp = "#ffc0b9" })
hi(0, "BufferLineErrorDiagnostic", { bg = "#0e1116", fg = "#c8d6e7", sp = "#bf908a" })
hi(0, "BufferLineErrorDiagnosticSelected", { bg = "#0e1118", bold = true, fg = "#ffc0b7", italic = true, sp = "#bf908a" })
hi(0, "BufferLineErrorDiagnosticVisible", { bg = "#0e1118", fg = "#c8d6e7" })
hi(0, "BufferLineErrorSelected", { bg = "#0e1118", bold = true, fg = "#ffc2ba", italic = true, sp = "#ffc0b9" })
hi(0, "BufferLineErrorVisible", { bg = "#0e1118", fg = "#c5d7eb" })
hi(0, "BufferLineFill", { bg = "#101115", fg = "#c5d7eb" })
hi(0, "BufferLineGroupLabel", { bg = "#0c1218", fg = "#d0d4e1" })
hi(0, "BufferLineGroupSeparator", { bg = "#101115", fg = "#c5d7eb" })
hi(0, "BufferLineHint", { bg = "#0e1116", fg = "#c5d7eb", sp = "#a6dbff" })
hi(0, "BufferLineHintDiagnostic", { bg = "#0e1116", fg = "#c8d6e7", sp = "#7ca4bf" })
hi(0, "BufferLineHintDiagnosticSelected", { bg = "#0e1118", bold = true, fg = "#a6dcff", italic = true, sp = "#7ca4bf" })
hi(0, "BufferLineHintDiagnosticVisible", { bg = "#0e1118", fg = "#c8d6e7" })
hi(0, "BufferLineHintSelected", { bg = "#0e1118", bold = true, fg = "#a5ddff", italic = true, sp = "#a6dbff" })
hi(0, "BufferLineHintVisible", { bg = "#0e1118", fg = "#c5d7eb" })
hi(0, "BufferLineIndicatorSelected", { bg = "#0e1118", fg = "#dbd5bf" })
hi(0, "BufferLineIndicatorVisible", { bg = "#0e1118", fg = "#cbd5e9" })
hi(0, "BufferLineInfo", { bg = "#0e1116", fg = "#c5d7eb", sp = "#8cf8f7" })
hi(0, "BufferLineInfoDiagnostic", { bg = "#0e1116", fg = "#c8d6e7", sp = "#69bab9" })
hi(0, "BufferLineInfoDiagnosticSelected", { bg = "#0e1118", bold = true, fg = "#84e9e7", italic = true, sp = "#69bab9" })
hi(0, "BufferLineInfoDiagnosticVisible", { bg = "#0e1118", fg = "#c8d6e7" })
hi(0, "BufferLineInfoSelected", { bg = "#0e1118", bold = true, fg = "#66edec", italic = true, sp = "#8cf8f7" })
hi(0, "BufferLineInfoVisible", { bg = "#0e1118", fg = "#c5d7eb" })
hi(0, "BufferLineModified", { bg = "#0e1116", fg = "#b5eb3e" })
hi(0, "BufferLineModifiedSelected", { bg = "#0e1118", fg = "#b5eb3e" })
hi(0, "BufferLineModifiedVisible", { bg = "#0e1118", fg = "#b5eb3e" })
hi(0, "BufferLineNumbers", { bg = "#0e1116", fg = "#c5d7eb" })
hi(0, "BufferLineNumbersSelected", { bg = "#0e1118", bold = true, fg = "#dbd5bf", italic = true })
hi(0, "BufferLineNumbersVisible", { bg = "#0e1118", fg = "#c5d7eb" })
hi(0, "BufferLineOffsetSeparator", { bg = "#101115", fg = "#dbd5bf" })
hi(0, "BufferLinePick", { bg = "#0e1116", bold = true, fg = "#ffc2ba", italic = true })
hi(0, "BufferLinePickSelected", { bg = "#0e1118", bold = true, fg = "#ffc2ba", italic = true })
hi(0, "BufferLinePickVisible", { bg = "#0e1118", bold = true, fg = "#ffc2ba", italic = true })
hi(0, "BufferLineSeparator", { bg = "#0e1116", fg = "#d0d4e1" })
hi(0, "BufferLineSeparatorSelected", { bg = "#0e1118", fg = "#d0d4e1" })
hi(0, "BufferLineSeparatorVisible", { bg = "#0e1118", fg = "#d0d4e1" })
hi(0, "BufferLineTab", { bg = "#0e1116", fg = "#c5d7eb" })
hi(0, "BufferLineTabClose", { bg = "#0e1116", fg = "#c5d7eb" })
hi(0, "BufferLineTabSelected", { bg = "#0e1118", fg = "#dbd5bf" })
hi(0, "BufferLineTabSeparator", { bg = "#0e1116", fg = "#d0d4e1" })
hi(0, "BufferLineTabSeparatorSelected", { bg = "#0e1118", fg = "#d0d4e1" })
hi(0, "BufferLineTruncMarker", { bg = "#101115", fg = "#c5d7eb" })
hi(0, "BufferLineWarning", { bg = "#0e1116", fg = "#c5d7eb", sp = "#fce094" })
hi(0, "BufferLineWarningDiagnostic", { bg = "#0e1116", fg = "#c8d6e7", sp = "#bda86f" })
hi(0, "BufferLineWarningDiagnosticSelected", { bg = "#0e1118", bold = true, fg = "#edd289", italic = true, sp = "#bda86f" })
hi(0, "BufferLineWarningDiagnosticVisible", { bg = "#0e1118", fg = "#c8d6e7" })
hi(0, "BufferLineWarningSelected", { bg = "#0e1118", bold = true, fg = "#f1d27a", italic = true, sp = "#fce094" })
hi(0, "BufferLineWarningVisible", { bg = "#0e1118", fg = "#c5d7eb" })
hi(0, "Changed", { ctermfg = 14, fg = "#66edec" })
hi(0, "ColorColumn", { bg = "#001321" })
hi(0, "Comment", { fg = "#c5d7eb", italic = true })
hi(0, "Conceal", { fg = "#c5d5f4" })
hi(0, "Conditional", { link = "Operator" })
hi(0, "Constant", { fg = "#d1d4e0" })
hi(0, "CurSearch", { bg = "#171000", ctermbg = 11, ctermfg = 0, fg = "#d0d4e3" })
hi(0, "Cursor", { bg = "#12110c", fg = "#cbd5e8" })
hi(0, "CursorColumn", { bg = "#0f1115" })
hi(0, "CursorLine", { bg = "#001321" })
hi(0, "CursorLineNr", { ctermfg = 12, fg = "#dbd5bf" })
hi(0, "Delimiter", { fg = "#d1d4e0" })
hi(0, "DiagnosticError", { ctermfg = 9, fg = "#ffc2ba" })
hi(0, "DiagnosticHint", { ctermfg = 12, fg = "#a5ddff" })
hi(0, "DiagnosticInfo", { ctermfg = 14, fg = "#66edec" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#9aebac" })
hi(0, "DiagnosticWarn", { ctermfg = 11, fg = "#f1d27a" })
hi(0, "DiffAdd", { bg = "#001612", ctermbg = 10, ctermfg = 0, fg = "#d1d5dd" })
hi(0, "DiffChange", { bg = "#0f1116", fg = "#d1d5dd" })
hi(0, "DiffDelete", { bg = "#200615", bold = true, ctermfg = 9, fg = "#ffc2ba" })
hi(0, "DiffText", { bg = "#001515", ctermbg = 14, ctermfg = 0, fg = "#d1d5dd" })
hi(0, "Directory", { ctermfg = 14, fg = "#66edec" })
hi(0, "Error", { bg = "#290002", ctermbg = 9, ctermfg = 0, fg = "#ffbeba" })
hi(0, "ErrorMsg", { ctermfg = 9, fg = "#ffc2ba" })
hi(0, "FloatShadow", { bg = "#0f1116", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#0f1116", blend = 100, ctermbg = 0 })
hi(0, "Folded", { fg = "#c5d7eb", italic = true })
hi(0, "Function", { ctermfg = 14, fg = "#bcd5ff" })
hi(0, "GitSignsStagedAdd", { fg = "#b2e3bb" })
hi(0, "GitSignsStagedAddCul", { fg = "#b2e3bb" })
hi(0, "GitSignsStagedAddLn", { bg = "#001612", fg = "#cdd3ed" })
hi(0, "GitSignsStagedAddNr", { fg = "#b2e3bb" })
hi(0, "GitSignsStagedChange", { fg = "#9fe3e2" })
hi(0, "GitSignsStagedChangeCul", { fg = "#9fe3e2" })
hi(0, "GitSignsStagedChangeLn", { bg = "#0f1116", fg = "#cdd3ed" })
hi(0, "GitSignsStagedChangeNr", { fg = "#9fe3e2" })
hi(0, "GitSignsStagedChangedelete", { fg = "#9fe3e2" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#9fe3e2" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#0f1116", fg = "#cdd3ed" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#9fe3e2" })
hi(0, "GitSignsStagedDelete", { fg = "#fdc5bd" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#fdc5bd" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#fdc5bd" })
hi(0, "GitSignsStagedTopdelete", { fg = "#fdc5bd" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#fdc5bd" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#fdc5bd" })
hi(0, "GitSignsStagedUntracked", { fg = "#b2e3bb" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#b2e3bb" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#001612", fg = "#cdd3ed" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#b2e3bb" })
hi(0, "Identifier", { ctermfg = 12, fg = "#dbd5bf" })
hi(0, "Keyword", { fg = "#a2deff" })
hi(0, "LineNr", { fg = "#c4d5f9" })
hi(0, "Macro", { link = "Function" })
hi(0, "MatchParen", { bg = "#0f1116", bold = true })
hi(0, "MiniHipatternsFixme", { bold = true, ctermfg = 9, fg = "#ffc2ba", reverse = true })
hi(0, "MiniHipatternsHack", { bold = true, ctermfg = 11, fg = "#f1d27a", reverse = true })
hi(0, "MiniHipatternsNote", { bold = true, ctermfg = 12, fg = "#a5ddff", reverse = true })
hi(0, "MiniHipatternsTodo", { bold = true, ctermfg = 14, fg = "#66edec", reverse = true })
hi(0, "ModeMsg", { ctermfg = 10, fg = "#9aebac" })
hi(0, "MoreMsg", { ctermfg = 14, fg = "#66edec" })
hi(0, "NoiceFormatProgressDone", { bg = "#171000", fg = "#d1d5dd" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#c5d7eb", italic = true })
hi(0, "Normal", { bg = "#0e1118", fg = "#dbd5bf" })
hi(0, "NormalFloat", { bg = "#0f1116" })
hi(0, "Number", { fg = "#e6c5ff" })
hi(0, "NvimInternalError", { bg = "#290000", ctermbg = 9, ctermfg = 9, fg = "#ffbfb3" })
hi(0, "Operator", { fg = "#a2deff" })
hi(0, "Pmenu", { bg = "#0e1118", fg = "#dbd5bf" })
hi(0, "PmenuSel", { bg = "#12110c", blend = 0, fg = "#cbd5e8", reverse = true })
hi(0, "PmenuThumb", { bg = "#0e1118", fg = "#dbd5bf" })
hi(0, "PreProc", { fg = "#d1d4e0" })
hi(0, "Question", { ctermfg = 14, fg = "#66edec" })
hi(0, "QuickFixLine", { ctermfg = 14, fg = "#66edec" })
hi(0, "RedrawDebugClear", { bg = "#171000", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#001705", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#290002", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 9, fg = "#ffc2ba" })
hi(0, "Repeat", { link = "Conditional" })
hi(0, "Search", { bg = "#171000", ctermbg = 11, ctermfg = 0, fg = "#d1d5dd" })
hi(0, "SignColumn", { bg = "#0e1118", fg = "#c5d5f4" })
hi(0, "SnacksBackdrop", { bg = "#111111" })
hi(0, "Special", { ctermfg = 14, fg = "#66edec" })
hi(0, "SpecialKey", { fg = "#c5d5f4" })
hi(0, "Statement", { bold = true, fg = "#d1d4e0" })
hi(0, "StatusLine", { bg = "#0d111a", fg = "#cbd5e7" })
hi(0, "StatusLineNC", { bg = "#0f1116", fg = "#d1d4e0" })
hi(0, "String", { ctermfg = 10, fg = "#b5eb3e" })
hi(0, "TSCharacter", { fg = "#84eccb" })
hi(0, "TSComment", { link = "Comment" })
hi(0, "TSConditional", { link = "Conditional" })
hi(0, "TSConstBuiltin", { link = "TSVariableBuiltin" })
hi(0, "TSConstant", { link = "Constant" })
hi(0, "TSField", { link = "Constant" })
hi(0, "TSFloat", { link = "Number" })
hi(0, "TSFuncMacro", { link = "Macro" })
hi(0, "TSFunction", { link = "Function" })
hi(0, "TSKeyword", { link = "Keyword" })
hi(0, "TSLabel", { link = "Type" })
hi(0, "TSNamespace", { link = "TSType" })
hi(0, "TSNumber", { link = "Number" })
hi(0, "TSOperator", { link = "Operator" })
hi(0, "TSParameter", { link = "Constant" })
hi(0, "TSParameterReference", { link = "TSParameter" })
hi(0, "TSProperty", { link = "TSField" })
hi(0, "TSPunctBracket", { link = "MyTag" })
hi(0, "TSPunctDelimiter", { fg = "#dbd5bf" })
hi(0, "TSPunctSpecial", { link = "TSPunctDelimiter" })
hi(0, "TSRepeat", { link = "Repeat" })
hi(0, "TSString", { link = "String" })
hi(0, "TSTag", { link = "MyTag" })
hi(0, "TSTagDelimiter", { link = "Type" })
hi(0, "TSType", { link = "Type" })
hi(0, "TabLine", { bg = "#0e1117", fg = "#c4d5fa" })
hi(0, "TabLineFill", { bg = "#0e1117", fg = "#c4d5fa" })
hi(0, "TabLineSel", { bg = "#12110c", bold = true, fg = "#cbd5e8" })
hi(0, "TelescopeNormal", { link = "Normal" })
hi(0, "Title", { bold = true, fg = "#d1d4e0" })
hi(0, "Todo", { bold = true, fg = "#d1d4e0" })
hi(0, "Type", { fg = "#dcc9ff", italic = true })
hi(0, "Visual", { bg = "#001321", ctermbg = 15, ctermfg = 0 })
hi(0, "WarningMsg", { ctermfg = 11, fg = "#f1d27a" })
hi(0, "Whitespace", { link = "Comment" })
hi(0, "WildMenu", { bg = "#0e1118", fg = "#dbd5bf" })
hi(0, "WinBar", { bg = "#0f1116", bold = true, fg = "#cbd5e9" })
hi(0, "WinBarNC", { bg = "#0f1116", fg = "#cbd5e9" })
hi(0, "lCursor", { bg = "#12110c", fg = "#cbd5e8" })
hi(0, "lualine_a_command", { bg = "#13110c", bold = true, fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_a_inactive", { bg = "#0e1119", bold = true, fg = "#c8d4f5", nocombine = true })
hi(0, "lualine_a_insert", { bg = "#0c1400", bold = true, fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_a_normal", { bg = "#0e1119", bold = true, fg = "#c8d4f5", nocombine = true })
hi(0, "lualine_a_replace", { bg = "#1e002b", bold = true, fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_a_terminal", { bg = "#13110c", bold = true, fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_a_visual", { bg = "#001515", bold = true, fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_b_command", { bg = "#0e1119", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_b_inactive", { bg = "#0e1119", fg = "#c8d4f5", nocombine = true })
hi(0, "lualine_b_insert", { bg = "#0e1119", fg = "#b3ec1e", nocombine = true })
hi(0, "lualine_b_normal", { bg = "#0e1119", fg = "#c8d4f5", nocombine = true })
hi(0, "lualine_b_replace", { bg = "#0e1119", fg = "#f1bfff", nocombine = true })
hi(0, "lualine_b_terminal", { bg = "#0e1119", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_b_visual", { bg = "#0e1119", fg = "#81e9e9", nocombine = true })
hi(0, "lualine_c_2_command", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_2_inactive", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_2_insert", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_2_normal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_2_replace", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_2_terminal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_2_visual", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_command", { bg = "#0d111a", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_c_diagnostics_error_command", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_c_diagnostics_error_inactive", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_c_diagnostics_error_insert", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_c_diagnostics_error_normal", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_c_diagnostics_error_replace", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_c_diagnostics_error_terminal", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_c_diagnostics_error_visual", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_command", { bg = "#0d111a", fg = "#a5ddff", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_inactive", { bg = "#0d111a", fg = "#a5ddff", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_insert", { bg = "#0d111a", fg = "#a5ddff", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_normal", { bg = "#0d111a", fg = "#a5ddff", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_replace", { bg = "#0d111a", fg = "#a5ddff", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_terminal", { bg = "#0d111a", fg = "#a5ddff", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_visual", { bg = "#0d111a", fg = "#a5ddff", nocombine = true })
hi(0, "lualine_c_diagnostics_info_command", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_diagnostics_info_inactive", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_diagnostics_info_insert", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_diagnostics_info_normal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_diagnostics_info_replace", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_diagnostics_info_terminal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_diagnostics_info_visual", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_command", { bg = "#0d111a", fg = "#f1d27a", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_inactive", { bg = "#0d111a", fg = "#f1d27a", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_insert", { bg = "#0d111a", fg = "#f1d27a", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_normal", { bg = "#0d111a", fg = "#f1d27a", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_replace", { bg = "#0d111a", fg = "#f1d27a", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_terminal", { bg = "#0d111a", fg = "#f1d27a", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_visual", { bg = "#0d111a", fg = "#f1d27a", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_0_1_command", { bg = "#0d111a", fg = "#bcd5ff", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_0_1_inactive", { bg = "#0d111a", fg = "#bcd5ff", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_0_1_insert", { bg = "#0d111a", fg = "#bcd5ff", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_0_1_normal", { bg = "#0d111a", fg = "#bcd5ff", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_0_1_replace", { bg = "#0d111a", fg = "#bcd5ff", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_0_1_terminal", { bg = "#0d111a", fg = "#bcd5ff", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_0_1_visual", { bg = "#0d111a", fg = "#bcd5ff", nocombine = true })
hi(0, "lualine_c_inactive", { bg = "#0d111a", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_c_insert", { bg = "#0d111a", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_c_normal", { bg = "#0d111a", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_c_replace", { bg = "#0d111a", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_c_terminal", { bg = "#0d111a", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_c_visual", { bg = "#0d111a", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#0e1119", fg = "#ddd4be", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_filetype_MiniIconsAzure_0_1_command", { bg = "#0d111a", fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_x_diff_removed_command", { bg = "#0d111a", fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_filetype_MiniIconsAzure_0_1_normal", { bg = "#0d111a", fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#0d111a", fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_11_normal", { bg = "#0d111a", fg = "#ccd4eb", nocombine = true })
hi(0, "lualine_x_10_command", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_10_inactive", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_10_insert", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_10_normal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_10_replace", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_10_terminal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_10_visual", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_11_command", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_11_inactive", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_11_insert", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_11_normal", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_11_replace", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_11_terminal", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_11_visual", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_12_command", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_12_inactive", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_12_insert", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_12_normal", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_12_replace", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_12_terminal", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_12_visual", { bg = "#0d111a", fg = "#d1d4e0", nocombine = true })
hi(0, "lualine_x_13_command", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_13_inactive", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_13_insert", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_13_normal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_13_replace", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_13_terminal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_13_visual", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_14_command", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_14_inactive", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_14_insert", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_14_normal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_14_replace", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_14_terminal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_14_visual", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_9", { link = "DiagnosticError" })
hi(0, "lualine_x_diff_added_command", { bg = "#0d111a", fg = "#9aebac", nocombine = true })
hi(0, "lualine_x_diff_added_inactive", { bg = "#0d111a", fg = "#9aebac", nocombine = true })
hi(0, "lualine_x_diff_added_insert", { bg = "#0d111a", fg = "#9aebac", nocombine = true })
hi(0, "lualine_x_diff_added_normal", { bg = "#0d111a", fg = "#9aebac", nocombine = true })
hi(0, "lualine_x_diff_added_replace", { bg = "#0d111a", fg = "#9aebac", nocombine = true })
hi(0, "lualine_x_diff_added_terminal", { bg = "#0d111a", fg = "#9aebac", nocombine = true })
hi(0, "lualine_x_diff_added_visual", { bg = "#0d111a", fg = "#9aebac", nocombine = true })
hi(0, "lualine_x_diff_modified_command", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_diff_modified_inactive", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_diff_modified_insert", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_diff_modified_normal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_diff_modified_replace", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_diff_modified_terminal", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_diff_modified_visual", { bg = "#0d111a", fg = "#66edec", nocombine = true })
hi(0, "lualine_x_diff_removed_command", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_x_diff_removed_inactive", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_x_diff_removed_insert", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_x_diff_removed_normal", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_x_diff_removed_replace", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_x_diff_removed_terminal", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })
hi(0, "lualine_x_diff_removed_visual", { bg = "#0d111a", fg = "#ffc2ba", nocombine = true })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1b1d2b"
g.terminal_color_1 = "#ff757f"
g.terminal_color_2 = "#c3e88d"
g.terminal_color_3 = "#ffc777"
g.terminal_color_4 = "#82aaff"
g.terminal_color_5 = "#c099ff"
g.terminal_color_6 = "#86e1fc"
g.terminal_color_7 = "#828bb8"
g.terminal_color_8 = "#444a73"
g.terminal_color_9 = "#ff8d94"
g.terminal_color_10 = "#c7fb6d"
g.terminal_color_11 = "#ffd8ab"
g.terminal_color_12 = "#9ab8ff"
g.terminal_color_13 = "#caabff"
g.terminal_color_14 = "#b2ebff"
g.terminal_color_15 = "#c8d3f5"
