-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "keppnns"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { link = "PreProc" })
hi(0, "@attribute", { link = "PreProc" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.printf", { link = "SpecialChar" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { fg = "#db30a4" })
hi(0, "@comment.hint", { fg = "#00bd9e" })
hi(0, "@comment.info", { fg = "#00b9d8" })
hi(0, "@comment.note", { fg = "#00bd9e" })
hi(0, "@comment.todo", { fg = "#6ba1ff" })
hi(0, "@comment.warning", { fg = "#d9b53e" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Define" })
hi(0, "@constructor", { fg = "#b597ff" })
hi(0, "@constructor.tsx", { fg = "#00c4e1" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "@function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "@function.method" })
hi(0, "@keyword", { fg = "#9876f3", italic = true })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { link = "Debug" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.function", { fg = "#b597ff" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { link = "@operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { link = "@keyword" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label", { fg = "#6ba1ff" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.deriveHelper", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.formatSpecifier", { link = "@markup.list" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.generic", { link = "@variable" })
hi(0, "@lsp.type.interface", { fg = "#16c8f1" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { sp = "#ca4d9d", undercurl = true })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.type.defaultLibrary", { fg = "#00a2bc" })
hi(0, "@lsp.typemod.typeAlias.defaultLibrary", { fg = "#00a2bc" })
hi(0, "@lsp.typemod.variable.callable", { link = "@function" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "@constant" })
hi(0, "@markup", { link = "@none" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "Type" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#6ba1ff" })
hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#d9b53e" })
hi(0, "@markup.heading.3.markdown", { bold = true, fg = "#86d551" })
hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#00bd9e" })
hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#b597ff" })
hi(0, "@markup.heading.6.markdown", { bold = true, fg = "#9876f3" })
hi(0, "@markup.heading.7.markdown", { bold = true, fg = "#e8ac3b" })
hi(0, "@markup.heading.8.markdown", { bold = true, fg = "#ec6bc4" })
hi(0, "@markup.link", { fg = "#00bd9e" })
hi(0, "@markup.link.label", { link = "SpecialChar" })
hi(0, "@markup.link.label.symbol", { link = "Identifier" })
hi(0, "@markup.link.url", { link = "Underlined" })
hi(0, "@markup.list", { fg = "#86ddff" })
hi(0, "@markup.list.checked", { fg = "#46e0ce" })
hi(0, "@markup.list.markdown", { bold = true, fg = "#e8ac3b" })
hi(0, "@markup.list.unchecked", { fg = "#6ba1ff" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@markup.raw.markdown_inline", { bg = "#474a53", fg = "#6ba1ff" })
hi(0, "@module", { link = "Include" })
hi(0, "@module.builtin", { fg = "#ec6bc4" })
hi(0, "@namespace.builtin", { link = "@variable.builtin" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { fg = "#86ddff" })
hi(0, "@property", { fg = "#46e0ce" })
hi(0, "@punctuation.bracket", { fg = "#a1b0e7" })
hi(0, "@punctuation.delimiter", { fg = "#86ddff" })
hi(0, "@punctuation.special", { fg = "#86ddff" })
hi(0, "@punctuation.special.markdown", { fg = "#e8ac3b" })
hi(0, "@string.documentation", { fg = "#d9b53e" })
hi(0, "@string.escape", { fg = "#b597ff" })
hi(0, "@string.regexp", { fg = "#a0fdfd" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@tag", { link = "Label" })
hi(0, "@tag.attribute", { link = "@property" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@tag.delimiter.tsx", { fg = "#4878d3" })
hi(0, "@tag.javascript", { fg = "#ec6bc4" })
hi(0, "@tag.tsx", { fg = "#ec6bc4" })
hi(0, "@type.builtin", { fg = "#00a2bc" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "@keyword" })
hi(0, "@variable", { fg = "#bacaff" })
hi(0, "@variable.builtin", { fg = "#ec6bc4" })
hi(0, "@variable.member", { fg = "#46e0ce" })
hi(0, "@variable.parameter", { fg = "#d9b53e" })
hi(0, "@variable.parameter.builtin", { fg = "#d7b863" })
hi(0, "Added", { ctermfg = 10, fg = "#9afdb9" })
hi(0, "BlinkCmpDoc", { fg = "#bacaff" })
hi(0, "BlinkCmpDocBorder", { fg = "#00a2bc" })
hi(0, "BlinkCmpGhostText", { fg = "#364483" })
hi(0, "BlinkCmpKindArray", { link = "LspKindArray" })
hi(0, "BlinkCmpKindBoolean", { link = "LspKindBoolean" })
hi(0, "BlinkCmpKindClass", { link = "LspKindClass" })
hi(0, "BlinkCmpKindCodeium", { fg = "#00bd9e" })
hi(0, "BlinkCmpKindColor", { link = "LspKindColor" })
hi(0, "BlinkCmpKindConstant", { link = "LspKindConstant" })
hi(0, "BlinkCmpKindConstructor", { link = "LspKindConstructor" })
hi(0, "BlinkCmpKindCopilot", { fg = "#00bd9e" })
hi(0, "BlinkCmpKindDefault", { fg = "#a1b0e7" })
hi(0, "BlinkCmpKindEnum", { link = "LspKindEnum" })
hi(0, "BlinkCmpKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "BlinkCmpKindEvent", { link = "LspKindEvent" })
hi(0, "BlinkCmpKindField", { link = "LspKindField" })
hi(0, "BlinkCmpKindFile", { link = "LspKindFile" })
hi(0, "BlinkCmpKindFolder", { link = "LspKindFolder" })
hi(0, "BlinkCmpKindFunction", { link = "LspKindFunction" })
hi(0, "BlinkCmpKindInterface", { link = "LspKindInterface" })
hi(0, "BlinkCmpKindKey", { link = "LspKindKey" })
hi(0, "BlinkCmpKindKeyword", { link = "LspKindKeyword" })
hi(0, "BlinkCmpKindMethod", { link = "LspKindMethod" })
hi(0, "BlinkCmpKindModule", { link = "LspKindModule" })
hi(0, "BlinkCmpKindNamespace", { link = "LspKindNamespace" })
hi(0, "BlinkCmpKindNull", { link = "LspKindNull" })
hi(0, "BlinkCmpKindNumber", { link = "LspKindNumber" })
hi(0, "BlinkCmpKindObject", { link = "LspKindObject" })
hi(0, "BlinkCmpKindOperator", { link = "LspKindOperator" })
hi(0, "BlinkCmpKindPackage", { link = "LspKindPackage" })
hi(0, "BlinkCmpKindProperty", { link = "LspKindProperty" })
hi(0, "BlinkCmpKindReference", { link = "LspKindReference" })
hi(0, "BlinkCmpKindSnippet", { link = "LspKindSnippet" })
hi(0, "BlinkCmpKindString", { link = "LspKindString" })
hi(0, "BlinkCmpKindStruct", { link = "LspKindStruct" })
hi(0, "BlinkCmpKindSupermaven", { fg = "#00bd9e" })
hi(0, "BlinkCmpKindTabNine", { fg = "#00bd9e" })
hi(0, "BlinkCmpKindText", { link = "LspKindText" })
hi(0, "BlinkCmpKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "BlinkCmpKindUnit", { link = "LspKindUnit" })
hi(0, "BlinkCmpKindValue", { link = "LspKindValue" })
hi(0, "BlinkCmpKindVariable", { link = "LspKindVariable" })
hi(0, "BlinkCmpLabel", { fg = "#bacaff" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#303e7a", strikethrough = true })
hi(0, "BlinkCmpLabelMatch", { fg = "#00c4e1" })
hi(0, "BlinkCmpMenu", { fg = "#bacaff" })
hi(0, "BlinkCmpMenuBorder", { fg = "#00a2bc" })
hi(0, "BlinkCmpSignatureHelp", { fg = "#bacaff" })
hi(0, "BlinkCmpSignatureHelpBorder", { fg = "#00a2bc" })
hi(0, "Bold", { bold = true, fg = "#bacaff" })
hi(0, "BufferLineBackground", { fg = "#485aa8" })
hi(0, "BufferLineBuffer", { fg = "#485aa8" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#bacaff", italic = true })
hi(0, "BufferLineBufferVisible", { fg = "#485aa8" })
hi(0, "BufferLineCloseButton", { fg = "#485aa8" })
hi(0, "BufferLineCloseButtonSelected", { fg = "#bacaff" })
hi(0, "BufferLineCloseButtonVisible", { fg = "#485aa8" })
hi(0, "BufferLineDiagnostic", { fg = "#344381" })
hi(0, "BufferLineDiagnosticSelected", { bold = true, fg = "#8796cd", italic = true })
hi(0, "BufferLineDiagnosticVisible", { fg = "#344381" })
hi(0, "BufferLineDuplicate", { fg = "#4355a2", italic = true })
hi(0, "BufferLineDuplicateSelected", { fg = "#4355a2", italic = true })
hi(0, "BufferLineDuplicateVisible", { fg = "#4355a2", italic = true })
hi(0, "BufferLineError", { fg = "#485aa8", sp = "#ca4d9d" })
hi(0, "BufferLineErrorDiagnostic", { fg = "#344381", sp = "#973a75" })
hi(0, "BufferLineErrorDiagnosticSelected", { bold = true, fg = "#a4247a", italic = true, sp = "#973a75" })
hi(0, "BufferLineErrorDiagnosticVisible", { fg = "#344381" })
hi(0, "BufferLineErrorSelected", { bold = true, fg = "#db30a4", italic = true, sp = "#ca4d9d" })
hi(0, "BufferLineErrorVisible", { fg = "#485aa8" })
hi(0, "BufferLineFill", { fg = "#485aa8" })
hi(0, "BufferLineGroupLabel", { bg = "#5c6171" })
hi(0, "BufferLineGroupSeparator", { fg = "#485aa8" })
hi(0, "BufferLineHint", { fg = "#485aa8", sp = "#12bc9e" })
hi(0, "BufferLineHintDiagnostic", { fg = "#344381", sp = "#0e8d77" })
hi(0, "BufferLineHintDiagnosticSelected", { bold = true, fg = "#008e77", italic = true, sp = "#0e8d77" })
hi(0, "BufferLineHintDiagnosticVisible", { fg = "#344381" })
hi(0, "BufferLineHintSelected", { bold = true, fg = "#00bd9e", italic = true, sp = "#12bc9e" })
hi(0, "BufferLineHintVisible", { fg = "#485aa8" })
hi(0, "BufferLineIndicatorSelected", { fg = "#4a82d4" })
hi(0, "BufferLineInfo", { fg = "#485aa8", sp = "#0cb9d7" })
hi(0, "BufferLineInfoDiagnostic", { fg = "#344381", sp = "#088aa1" })
hi(0, "BufferLineInfoDiagnosticSelected", { bold = true, fg = "#008aa2", italic = true, sp = "#088aa1" })
hi(0, "BufferLineInfoDiagnosticVisible", { fg = "#344381" })
hi(0, "BufferLineInfoSelected", { bold = true, fg = "#00b9d8", italic = true, sp = "#0cb9d7" })
hi(0, "BufferLineInfoVisible", { fg = "#485aa8" })
hi(0, "BufferLineMiniIconsAzureSelected", { fg = "#00b9d8" })
hi(0, "BufferLineModified", { fg = "#86d551" })
hi(0, "BufferLineModifiedSelected", { fg = "#86d551" })
hi(0, "BufferLineModifiedVisible", { fg = "#86d551" })
hi(0, "BufferLineNumbers", { fg = "#485aa8" })
hi(0, "BufferLineNumbersSelected", { bold = true, fg = "#bacaff", italic = true })
hi(0, "BufferLineNumbersVisible", { fg = "#485aa8" })
hi(0, "BufferLineOffsetSeparator", { fg = "#7b78c4" })
hi(0, "BufferLinePick", { bold = true, fg = "#db30a4", italic = true })
hi(0, "BufferLinePickSelected", { bold = true, fg = "#db30a4", italic = true })
hi(0, "BufferLinePickVisible", { bold = true, fg = "#db30a4", italic = true })
hi(0, "BufferLineTab", { fg = "#485aa8" })
hi(0, "BufferLineTabClose", { fg = "#485aa8" })
hi(0, "BufferLineTabSelected", { fg = "#6ba1ff" })
hi(0, "BufferLineTruncMarker", { fg = "#485aa8" })
hi(0, "BufferLineWarning", { fg = "#485aa8", sp = "#d1b765" })
hi(0, "BufferLineWarningDiagnostic", { fg = "#344381", sp = "#9d894c" })
hi(0, "BufferLineWarningDiagnosticSelected", { bold = true, fg = "#a3882f", italic = true, sp = "#9d894c" })
hi(0, "BufferLineWarningDiagnosticVisible", { fg = "#344381" })
hi(0, "BufferLineWarningSelected", { bold = true, fg = "#d9b53e", italic = true, sp = "#d1b765" })
hi(0, "BufferLineWarningVisible", { fg = "#485aa8" })
hi(0, "Changed", { ctermfg = 14, fg = "#65fdfe" })
hi(0, "Character", { fg = "#86d551" })
hi(0, "ColorColumn", { bg = "#171717" })
hi(0, "Comment", { fg = "#485aa8", italic = true })
hi(0, "Conceal", { fg = "#6877bd" })
hi(0, "Constant", { fg = "#e8ac3b" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#c1ccec", fg = "#161a32" })
hi(0, "CursorColumn", { bg = "#2e2f33" })
hi(0, "CursorIM", { bg = "#c1ccec", fg = "#161a32" })
hi(0, "CursorLine", { bg = "#2e2f33" })
hi(0, "CursorLineNr", { bold = true, fg = "#e8ac3b" })
hi(0, "DapStoppedLine", { bg = "#2b2b2b" })
hi(0, "Debug", { fg = "#e8ac3b" })
hi(0, "Delimiter", { link = "Special" })
hi(0, "DiagnosticDeprecated", { sp = "#f6bfdd", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#db30a4" })
hi(0, "DiagnosticHint", { fg = "#00bd9e" })
hi(0, "DiagnosticInfo", { fg = "#00b9d8" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#9afdb9" })
hi(0, "DiagnosticUnderlineError", { sp = "#ca4d9d", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#12bc9e", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#0cb9d7", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#aff7c3", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#d1b765", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#364483" })
hi(0, "DiagnosticVirtualTextError", { bg = "#272328", fg = "#db30a4" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#1f2a2f", fg = "#00bd9e" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#1e2a34", fg = "#00b9d8" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#2b2b2b", fg = "#d9b53e" })
hi(0, "DiagnosticWarn", { fg = "#d9b53e" })
hi(0, "DiffAdd", { bg = "#252f36" })
hi(0, "DiffChange", { bg = "#222325" })
hi(0, "DiffDelete", { bg = "#2f262e" })
hi(0, "DiffText", { bg = "#424c5d" })
hi(0, "Directory", { fg = "#6ba1ff" })
hi(0, "EndOfBuffer", { fg = "#161a32" })
hi(0, "Error", { fg = "#db30a4" })
hi(0, "ErrorMsg", { fg = "#db30a4" })
hi(0, "FlashBackdrop", { fg = "#47589e" })
hi(0, "FlashLabel", { bg = "#dd47ba", bold = true, fg = "#bacaff" })
hi(0, "FloatBorder", { fg = "#00a2bc" })
hi(0, "FloatShadow", { bg = "#525252", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#525252", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { fg = "#00a2bc" })
hi(0, "FoldColumn", { fg = "#485aa8" })
hi(0, "Folded", { bg = "#41444d", fg = "#6ba1ff" })
hi(0, "Foo", { bg = "#dd47ba", fg = "#bacaff" })
hi(0, "Function", { fg = "#6ba1ff" })
hi(0, "FzfLuaBorder", { fg = "#00a2bc" })
hi(0, "FzfLuaCursor", { link = "IncSearch" })
hi(0, "FzfLuaDirPart", { fg = "#a1b0e7" })
hi(0, "FzfLuaFilePart", { link = "FzfLuaFzfNormal" })
hi(0, "FzfLuaFzfCursorLine", { link = "Visual" })
hi(0, "FzfLuaFzfNormal", { fg = "#bacaff" })
hi(0, "FzfLuaFzfPointer", { fg = "#e82ac1" })
hi(0, "FzfLuaFzfSeparator", { fg = "#e8ac3b" })
hi(0, "FzfLuaHeaderBind", { link = "@punctuation.special" })
hi(0, "FzfLuaHeaderText", { link = "Title" })
hi(0, "FzfLuaNormal", { fg = "#bacaff" })
hi(0, "FzfLuaPath", { link = "Directory" })
hi(0, "FzfLuaPreviewTitle", { fg = "#00a2bc" })
hi(0, "FzfLuaTitle", { fg = "#e8ac3b" })
hi(0, "GitSignsAdd", { fg = "#13a0b2" })
hi(0, "GitSignsChange", { fg = "#4a82d4" })
hi(0, "GitSignsDelete", { fg = "#954078" })
hi(0, "GitSignsStagedAdd", { fg = "#0d5059" })
hi(0, "GitSignsStagedAddCul", { fg = "#0d5059" })
hi(0, "GitSignsStagedAddLn", { bg = "#252f36" })
hi(0, "GitSignsStagedAddNr", { fg = "#0d5059" })
hi(0, "GitSignsStagedChange", { fg = "#22416d" })
hi(0, "GitSignsStagedChangeCul", { fg = "#22416d" })
hi(0, "GitSignsStagedChangeLn", { bg = "#222325" })
hi(0, "GitSignsStagedChangeNr", { fg = "#22416d" })
hi(0, "GitSignsStagedChangedelete", { fg = "#22416d" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#22416d" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#222325" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#22416d" })
hi(0, "GitSignsStagedDelete", { fg = "#4b1f3c" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#4b1f3c" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#4b1f3c" })
hi(0, "GitSignsStagedTopdelete", { fg = "#4b1f3c" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#4b1f3c" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#4b1f3c" })
hi(0, "GitSignsStagedUntracked", { fg = "#0d5059" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#0d5059" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#252f36" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#0d5059" })
hi(0, "GrugFarHelpHeader", { fg = "#485aa8" })
hi(0, "GrugFarHelpHeaderKey", { fg = "#79cffe" })
hi(0, "GrugFarInputLabel", { fg = "#00c4e1" })
hi(0, "GrugFarInputPlaceholder", { fg = "#47589e" })
hi(0, "GrugFarResultsChangeIndicator", { fg = "#4a82d4" })
hi(0, "GrugFarResultsHeader", { fg = "#e8ac3b" })
hi(0, "GrugFarResultsLineColumn", { fg = "#47589e" })
hi(0, "GrugFarResultsLineNo", { fg = "#47589e" })
hi(0, "GrugFarResultsMatch", { bg = "#dc83bd", fg = "#121429" })
hi(0, "GrugFarResultsStats", { fg = "#6ba1ff" })
hi(0, "Identifier", { fg = "#b597ff" })
hi(0, "IncSearch", { bg = "#e1b05e", fg = "#121429" })
hi(0, "Italic", { fg = "#bacaff", italic = true })
hi(0, "Keyword", { fg = "#79cffe", italic = true })
hi(0, "LazyProgressDone", { bold = true, fg = "#e82ac1" })
hi(0, "LazyProgressTodo", { bold = true, fg = "#303e7a" })
hi(0, "LineNr", { fg = "#303e7a" })
hi(0, "LineNrAbove", { fg = "#303e7a" })
hi(0, "LineNrBelow", { fg = "#303e7a" })
hi(0, "LspCodeLens", { fg = "#485aa8" })
hi(0, "LspInfoBorder", { fg = "#00a2bc" })
hi(0, "LspInlayHint", { bg = "#202122", fg = "#47589e" })
hi(0, "LspKindArray", { link = "@punctuation.bracket" })
hi(0, "LspKindBoolean", { link = "@boolean" })
hi(0, "LspKindClass", { link = "@type" })
hi(0, "LspKindColor", { link = "Special" })
hi(0, "LspKindConstant", { link = "@constant" })
hi(0, "LspKindConstructor", { link = "@constructor" })
hi(0, "LspKindEnum", { link = "@lsp.type.enum" })
hi(0, "LspKindEnumMember", { link = "@lsp.type.enumMember" })
hi(0, "LspKindEvent", { link = "Special" })
hi(0, "LspKindField", { link = "@variable.member" })
hi(0, "LspKindFile", { link = "Normal" })
hi(0, "LspKindFolder", { link = "Directory" })
hi(0, "LspKindFunction", { link = "@function" })
hi(0, "LspKindInterface", { link = "@lsp.type.interface" })
hi(0, "LspKindKey", { link = "@variable.member" })
hi(0, "LspKindKeyword", { link = "@lsp.type.keyword" })
hi(0, "LspKindMethod", { link = "@function.method" })
hi(0, "LspKindModule", { link = "@module" })
hi(0, "LspKindNamespace", { link = "@module" })
hi(0, "LspKindNull", { link = "@constant.builtin" })
hi(0, "LspKindNumber", { link = "@number" })
hi(0, "LspKindObject", { link = "@constant" })
hi(0, "LspKindOperator", { link = "@operator" })
hi(0, "LspKindPackage", { link = "@module" })
hi(0, "LspKindProperty", { link = "@property" })
hi(0, "LspKindReference", { link = "@markup.link" })
hi(0, "LspKindSnippet", { link = "Conceal" })
hi(0, "LspKindString", { link = "@string" })
hi(0, "LspKindStruct", { link = "@lsp.type.struct" })
hi(0, "LspKindText", { link = "@markup" })
hi(0, "LspKindTypeParameter", { link = "@lsp.type.typeParameter" })
hi(0, "LspKindUnit", { link = "@lsp.type.struct" })
hi(0, "LspKindValue", { link = "@string" })
hi(0, "LspKindVariable", { link = "@variable" })
hi(0, "LspReferenceRead", { bg = "#41444d" })
hi(0, "LspReferenceText", { bg = "#41444d" })
hi(0, "LspReferenceWrite", { bg = "#41444d" })
hi(0, "LspSignatureActiveParameter", { bg = "#24262d", bold = true })
hi(0, "MatchParen", { bold = true, fg = "#e8ac3b" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#bacaff" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bold = true, fg = "#00a2bc" })
hi(0, "MiniHipatternsFixme", { bg = "#be5d98", bold = true, fg = "#121429" })
hi(0, "MiniHipatternsHack", { bg = "#cbb87c", bold = true, fg = "#121429" })
hi(0, "MiniHipatternsNote", { bg = "#44b89f", bold = true, fg = "#121429" })
hi(0, "MiniHipatternsTodo", { bg = "#44b7d0", bold = true, fg = "#121429" })
hi(0, "MiniIconsAzure", { fg = "#00b9d8" })
hi(0, "MiniIconsBlue", { fg = "#6ba1ff" })
hi(0, "MiniIconsCyan", { fg = "#00bd9e" })
hi(0, "MiniIconsGreen", { fg = "#86d551" })
hi(0, "MiniIconsGrey", { fg = "#bacaff" })
hi(0, "MiniIconsOrange", { fg = "#e8ac3b" })
hi(0, "MiniIconsPurple", { fg = "#9876f3" })
hi(0, "MiniIconsRed", { fg = "#ec6bc4" })
hi(0, "MiniIconsYellow", { fg = "#d9b53e" })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#d9b53e", italic = true })
hi(0, "MiniStarterHeader", { fg = "#6ba1ff" })
hi(0, "MiniStarterInactive", { fg = "#485aa8", italic = true })
hi(0, "MiniStarterItem", { fg = "#bacaff" })
hi(0, "MiniStarterItemBullet", { fg = "#00a2bc" })
hi(0, "MiniStarterItemPrefix", { fg = "#d9b53e" })
hi(0, "MiniStarterQuery", { fg = "#00b9d8" })
hi(0, "MiniStarterSection", { fg = "#00c4e1" })
hi(0, "MiniSurround", { bg = "#e1b05e", fg = "#121429" })
hi(0, "ModeMsg", { bold = true, fg = "#a1b0e7" })
hi(0, "MoreMsg", { fg = "#6ba1ff" })
hi(0, "MsgArea", { fg = "#a1b0e7" })
hi(0, "NeoTreeDimText", { fg = "#303e7a" })
hi(0, "NeoTreeFileName", { fg = "#a1b0e7" })
hi(0, "NeoTreeGitModified", { fg = "#e8ac3b" })
hi(0, "NeoTreeGitStaged", { fg = "#46e0ce" })
hi(0, "NeoTreeGitUntracked", { fg = "#b597ff" })
hi(0, "NeoTreeNormal", { fg = "#a1b0e7" })
hi(0, "NeoTreeNormalNC", { fg = "#a1b0e7" })
hi(0, "NeoTreeTabActive", { bg = "#171717", bold = true, fg = "#6ba1ff" })
hi(0, "NeoTreeTabInactive", { fg = "#47589e" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#171717", fg = "#6ba1ff" })
hi(0, "NeoTreeTabSeparatorInactive", { fg = "#161a32" })
hi(0, "NoiceAttr95", { fg = "#db30a4" })
hi(0, "NoiceCmdlineIconInput", { fg = "#d9b53e" })
hi(0, "NoiceCmdlineIconLua", { fg = "#00c4e1" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#d9b53e" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#00c4e1" })
hi(0, "NoiceCmdlinePopupTitleInput", { fg = "#d9b53e" })
hi(0, "NoiceCmdlinePopupTitleLua", { fg = "#00c4e1" })
hi(0, "NoiceCompletionItemKindArray", { link = "LspKindArray" })
hi(0, "NoiceCompletionItemKindBoolean", { link = "LspKindBoolean" })
hi(0, "NoiceCompletionItemKindClass", { link = "LspKindClass" })
hi(0, "NoiceCompletionItemKindColor", { link = "LspKindColor" })
hi(0, "NoiceCompletionItemKindConstant", { link = "LspKindConstant" })
hi(0, "NoiceCompletionItemKindConstructor", { link = "LspKindConstructor" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#a1b0e7" })
hi(0, "NoiceCompletionItemKindEnum", { link = "LspKindEnum" })
hi(0, "NoiceCompletionItemKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "NoiceCompletionItemKindEvent", { link = "LspKindEvent" })
hi(0, "NoiceCompletionItemKindField", { link = "LspKindField" })
hi(0, "NoiceCompletionItemKindFile", { link = "LspKindFile" })
hi(0, "NoiceCompletionItemKindFolder", { link = "LspKindFolder" })
hi(0, "NoiceCompletionItemKindFunction", { link = "LspKindFunction" })
hi(0, "NoiceCompletionItemKindInterface", { link = "LspKindInterface" })
hi(0, "NoiceCompletionItemKindKey", { link = "LspKindKey" })
hi(0, "NoiceCompletionItemKindKeyword", { link = "LspKindKeyword" })
hi(0, "NoiceCompletionItemKindMethod", { link = "LspKindMethod" })
hi(0, "NoiceCompletionItemKindModule", { link = "LspKindModule" })
hi(0, "NoiceCompletionItemKindNamespace", { link = "LspKindNamespace" })
hi(0, "NoiceCompletionItemKindNull", { link = "LspKindNull" })
hi(0, "NoiceCompletionItemKindNumber", { link = "LspKindNumber" })
hi(0, "NoiceCompletionItemKindObject", { link = "LspKindObject" })
hi(0, "NoiceCompletionItemKindOperator", { link = "LspKindOperator" })
hi(0, "NoiceCompletionItemKindPackage", { link = "LspKindPackage" })
hi(0, "NoiceCompletionItemKindProperty", { link = "LspKindProperty" })
hi(0, "NoiceCompletionItemKindReference", { link = "LspKindReference" })
hi(0, "NoiceCompletionItemKindSnippet", { link = "LspKindSnippet" })
hi(0, "NoiceCompletionItemKindString", { link = "LspKindString" })
hi(0, "NoiceCompletionItemKindStruct", { link = "LspKindStruct" })
hi(0, "NoiceCompletionItemKindText", { link = "LspKindText" })
hi(0, "NoiceCompletionItemKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "NoiceCompletionItemKindUnit", { link = "LspKindUnit" })
hi(0, "NoiceCompletionItemKindValue", { link = "LspKindValue" })
hi(0, "NoiceCompletionItemKindVariable", { link = "LspKindVariable" })
hi(0, "NoiceFormatProgressDone", { bg = "#475d89", fg = "#bacaff" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#47589e" })
hi(0, "Normal", { fg = "#bacaff" })
hi(0, "NormalFloat", { fg = "#bacaff" })
hi(0, "NormalNC", { fg = "#bacaff" })
hi(0, "NormalSB", { fg = "#a1b0e7" })
hi(0, "NvimInternalError", { bg = "#dd3ea6", ctermbg = 9, ctermfg = 9, fg = "#e918ab" })
hi(0, "Operator", { fg = "#86ddff" })
hi(0, "Pmenu", { bg = "#171717", fg = "#bacaff" })
hi(0, "PmenuMatch", { bg = "#171717", fg = "#00c4e1" })
hi(0, "PmenuMatchSel", { bg = "#393b43", fg = "#00c4e1" })
hi(0, "PmenuSbar", { bg = "#202020" })
hi(0, "PmenuSel", { bg = "#393b43" })
hi(0, "PmenuThumb", { bg = "#41444d" })
hi(0, "PreProc", { fg = "#79cffe" })
hi(0, "Question", { fg = "#6ba1ff" })
hi(0, "QuickFixLine", { bg = "#2e3646", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#6ba1ff" })
hi(0, "RainbowDelimiterCyan", { fg = "#79cffe" })
hi(0, "RainbowDelimiterGreen", { fg = "#86d551" })
hi(0, "RainbowDelimiterOrange", { fg = "#e8ac3b" })
hi(0, "RainbowDelimiterRed", { fg = "#ec6bc4" })
hi(0, "RainbowDelimiterViolet", { fg = "#9876f3" })
hi(0, "RainbowDelimiterYellow", { fg = "#d9b53e" })
hi(0, "RedrawDebugClear", { bg = "#60581c", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#10532c", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#4c1037", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 9, fg = "#f6badb" })
hi(0, "RenderMarkdownBullet", { fg = "#e8ac3b" })
hi(0, "RenderMarkdownCode", { bg = "#171717" })
hi(0, "RenderMarkdownCodeInline", { link = "@markup.raw.markdown_inline" })
hi(0, "RenderMarkdownDash", { fg = "#e8ac3b" })
hi(0, "RenderMarkdownH1Bg", { bg = "#292a2d" })
hi(0, "RenderMarkdownH1Fg", { bold = true, fg = "#6ba1ff" })
hi(0, "RenderMarkdownH2Bg", { bg = "#2b2b2b" })
hi(0, "RenderMarkdownH2Fg", { bold = true, fg = "#d9b53e" })
hi(0, "RenderMarkdownH3Bg", { bg = "#2b2c2c" })
hi(0, "RenderMarkdownH3Fg", { bold = true, fg = "#86d551" })
hi(0, "RenderMarkdownH4Bg", { bg = "#1f2a2f" })
hi(0, "RenderMarkdownH4Fg", { bold = true, fg = "#00bd9e" })
hi(0, "RenderMarkdownH5Bg", { bg = "#2a2a2f" })
hi(0, "RenderMarkdownH5Fg", { bold = true, fg = "#b597ff" })
hi(0, "RenderMarkdownH6Bg", { bg = "#27272d" })
hi(0, "RenderMarkdownH6Fg", { bold = true, fg = "#9876f3" })
hi(0, "RenderMarkdownH7Bg", { bg = "#2b2b2b" })
hi(0, "RenderMarkdownH7Fg", { bold = true, fg = "#e8ac3b" })
hi(0, "RenderMarkdownH8Bg", { bg = "#2a272c" })
hi(0, "RenderMarkdownH8Fg", { bold = true, fg = "#ec6bc4" })
hi(0, "RenderMarkdownTableHead", { fg = "#ec6bc4" })
hi(0, "RenderMarkdownTableRow", { fg = "#e8ac3b" })
hi(0, "Search", { bg = "#475d89", fg = "#bacaff" })
hi(0, "SignColumn", { fg = "#303e7a" })
hi(0, "SignColumnSB", { fg = "#303e7a" })
hi(0, "SmearCursor", { blend = 0, ctermfg = 255, fg = "#bacaff" })
hi(0, "SmearCursor1", { blend = 0, ctermfg = 240, fg = "#4c5a89" })
hi(0, "SmearCursor10", { blend = 0, ctermfg = 249, fg = "#9cabe1" })
hi(0, "SmearCursor10_bb9af7", { blend = 0, ctermfg = 249, fg = "#9b80ec" })
hi(0, "SmearCursor11", { blend = 0, ctermfg = 250, fg = "#a1b2e7" })
hi(0, "SmearCursor11_bb9af7", { blend = 0, ctermfg = 250, fg = "#a084f2" })
hi(0, "SmearCursor12", { blend = 0, ctermfg = 251, fg = "#a6b7ed" })
hi(0, "SmearCursor12_bb9af7", { blend = 0, ctermfg = 251, fg = "#a588f8" })
hi(0, "SmearCursor13", { blend = 0, ctermfg = 252, fg = "#acbcf1" })
hi(0, "SmearCursor13_bb9af7", { blend = 0, ctermfg = 252, fg = "#a98bfd" })
hi(0, "SmearCursor14", { blend = 0, ctermfg = 253, fg = "#b1c1f6" })
hi(0, "SmearCursor14_bb9af7", { blend = 0, ctermfg = 253, fg = "#ad90ff" })
hi(0, "SmearCursor15", { blend = 0, ctermfg = 254, fg = "#b5c6fb" })
hi(0, "SmearCursor15_bb9af7", { blend = 0, ctermfg = 254, fg = "#b193ff" })
hi(0, "SmearCursor16", { blend = 0, ctermfg = 255, fg = "#bacaff" })
hi(0, "SmearCursor16_bb9af7", { blend = 0, ctermfg = 255, fg = "#b597ff" })
hi(0, "SmearCursor1_bb9af7", { blend = 0, ctermfg = 240, fg = "#574980" })
hi(0, "SmearCursor2", { blend = 0, ctermfg = 241, fg = "#5c6a9c" })
hi(0, "SmearCursor2_bb9af7", { blend = 0, ctermfg = 241, fg = "#655298" })
hi(0, "SmearCursor3", { blend = 0, ctermfg = 242, fg = "#6776a8" })
hi(0, "SmearCursor3_bb9af7", { blend = 0, ctermfg = 242, fg = "#705aab" })
hi(0, "SmearCursor4", { blend = 0, ctermfg = 243, fg = "#7380b3" })
hi(0, "SmearCursor4_bb9af7", { blend = 0, ctermfg = 243, fg = "#7960ba" })
hi(0, "SmearCursor5", { blend = 0, ctermfg = 244, fg = "#7b8abd" })
hi(0, "SmearCursor5_bb9af7", { blend = 0, ctermfg = 244, fg = "#8066c4" })
hi(0, "SmearCursor6", { blend = 0, ctermfg = 245, fg = "#8292c5" })
hi(0, "SmearCursor6_bb9af7", { blend = 0, ctermfg = 245, fg = "#876dcd" })
hi(0, "SmearCursor7", { blend = 0, ctermfg = 246, fg = "#8999cd" })
hi(0, "SmearCursor7_bb9af7", { blend = 0, ctermfg = 246, fg = "#8c72d6" })
hi(0, "SmearCursor8", { blend = 0, ctermfg = 247, fg = "#909fd4" })
hi(0, "SmearCursor8_bb9af7", { blend = 0, ctermfg = 247, fg = "#9277dd" })
hi(0, "SmearCursor9", { blend = 0, ctermfg = 248, fg = "#96a6db" })
hi(0, "SmearCursor9_bb9af7", { blend = 0, ctermfg = 248, fg = "#977ce4" })
hi(0, "SmearCursorInverted1", { bg = "#5c5c5c", blend = 0, ctermbg = 240, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted10", { bg = "#a7adc1", blend = 0, ctermbg = 249, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted10_bb9af7", { bg = "#988dc2", blend = 0, ctermbg = 249, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted11", { bg = "#acb3c9", blend = 0, ctermbg = 250, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted11_bb9af7", { bg = "#9d90cb", blend = 0, ctermbg = 250, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted12", { bg = "#b1b8d1", blend = 0, ctermbg = 251, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted12_bb9af7", { bg = "#a194d3", blend = 0, ctermbg = 251, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted13", { bg = "#b5bed8", blend = 0, ctermbg = 252, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted13_bb9af7", { bg = "#a597d9", blend = 0, ctermbg = 252, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted14", { bg = "#b9c3df", blend = 0, ctermbg = 253, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted14_bb9af7", { bg = "#aa9be0", blend = 0, ctermbg = 253, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted15", { bg = "#bdc8e6", blend = 0, ctermbg = 254, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted15_bb9af7", { bg = "#ad9ee7", blend = 0, ctermbg = 254, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted16", { bg = "#c1ccec", blend = 0, ctermbg = 255, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted16_bb9af7", { bg = "#b1a0ed", blend = 0, ctermbg = 255, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted1_bb9af7", { bg = "#535257", blend = 0, ctermbg = 240, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted2", { bg = "#6d6d6d", blend = 0, ctermbg = 241, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted2_bb9af7", { bg = "#615e6b", blend = 0, ctermbg = 241, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted3", { bg = "#797979", blend = 0, ctermbg = 242, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted3_bb9af7", { bg = "#6b6979", blend = 0, ctermbg = 242, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted4", { bg = "#838384", blend = 0, ctermbg = 243, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted4_bb9af7", { bg = "#746f85", blend = 0, ctermbg = 243, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted5", { bg = "#8b8c91", blend = 0, ctermbg = 244, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted5_bb9af7", { bg = "#7b7591", blend = 0, ctermbg = 244, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted6", { bg = "#92949c", blend = 0, ctermbg = 245, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted6_bb9af7", { bg = "#827b9d", blend = 0, ctermbg = 245, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted7", { bg = "#979ba6", blend = 0, ctermbg = 246, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted7_bb9af7", { bg = "#8780a8", blend = 0, ctermbg = 246, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted8", { bg = "#9ca1b0", blend = 0, ctermbg = 247, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted8_bb9af7", { bg = "#8d84b1", blend = 0, ctermbg = 247, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted9", { bg = "#a2a8b9", blend = 0, ctermbg = 248, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursorInverted9_bb9af7", { bg = "#9489ba", blend = 0, ctermbg = 248, ctermfg = 235, fg = "#303030" })
hi(0, "SmearCursor_bb9af7", { blend = 0, ctermfg = 255, fg = "#b597ff" })
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksDashboardDesc", { fg = "#79cffe" })
hi(0, "SnacksDashboardDir", { fg = "#47589e" })
hi(0, "SnacksDashboardFooter", { fg = "#00c4e1" })
hi(0, "SnacksDashboardHeader", { fg = "#6ba1ff" })
hi(0, "SnacksDashboardIcon", { fg = "#00c4e1" })
hi(0, "SnacksDashboardKey", { fg = "#e8ac3b" })
hi(0, "SnacksDashboardSpecial", { fg = "#9876f3" })
hi(0, "SnacksIndent", { fg = "#303e7a", nocombine = true })
hi(0, "SnacksIndent1", { fg = "#6ba1ff", nocombine = true })
hi(0, "SnacksIndent2", { fg = "#d9b53e", nocombine = true })
hi(0, "SnacksIndent3", { fg = "#86d551", nocombine = true })
hi(0, "SnacksIndent4", { fg = "#00bd9e", nocombine = true })
hi(0, "SnacksIndent5", { fg = "#b597ff", nocombine = true })
hi(0, "SnacksIndent6", { fg = "#9876f3", nocombine = true })
hi(0, "SnacksIndent7", { fg = "#e8ac3b", nocombine = true })
hi(0, "SnacksIndent8", { fg = "#ec6bc4", nocombine = true })
hi(0, "SnacksIndentScope", { fg = "#00c4e1", nocombine = true })
hi(0, "SnacksInputBorder", { fg = "#d9b53e" })
hi(0, "SnacksInputIcon", { fg = "#00c4e1" })
hi(0, "SnacksInputTitle", { fg = "#d9b53e" })
hi(0, "SnacksNotifierBorderDebug", { fg = "#2a3363" })
hi(0, "SnacksNotifierBorderError", { fg = "#692553" })
hi(0, "SnacksNotifierBorderInfo", { fg = "#005b70" })
hi(0, "SnacksNotifierBorderTrace", { fg = "#4c3c84" })
hi(0, "SnacksNotifierBorderWarn", { fg = "#685830" })
hi(0, "SnacksNotifierDebug", { fg = "#bacaff" })
hi(0, "SnacksNotifierError", { fg = "#bacaff" })
hi(0, "SnacksNotifierIconDebug", { fg = "#485aa8" })
hi(0, "SnacksNotifierIconError", { fg = "#db30a4" })
hi(0, "SnacksNotifierIconInfo", { fg = "#00b9d8" })
hi(0, "SnacksNotifierIconTrace", { fg = "#9876f3" })
hi(0, "SnacksNotifierIconWarn", { fg = "#d9b53e" })
hi(0, "SnacksNotifierInfo", { fg = "#bacaff" })
hi(0, "SnacksNotifierTitleDebug", { fg = "#485aa8" })
hi(0, "SnacksNotifierTitleError", { fg = "#db30a4" })
hi(0, "SnacksNotifierTitleInfo", { fg = "#00b9d8" })
hi(0, "SnacksNotifierTitleTrace", { fg = "#9876f3" })
hi(0, "SnacksNotifierTitleWarn", { fg = "#d9b53e" })
hi(0, "SnacksNotifierTrace", { fg = "#bacaff" })
hi(0, "SnacksNotifierWarn", { fg = "#bacaff" })
hi(0, "SnacksPickerBoxTitle", { fg = "#e8ac3b" })
hi(0, "SnacksPickerFlag", { link = "SnacksProfilerBadgeInfo" })
hi(0, "SnacksPickerInputBorder", { fg = "#e8ac3b" })
hi(0, "SnacksPickerInputTitle", { fg = "#e8ac3b" })
hi(0, "SnacksPickerPickWin", { bg = "#475d89", bold = true, fg = "#bacaff" })
hi(0, "SnacksPickerPickWinCurrent", { bg = "#dd47ba", bold = true, fg = "#bacaff" })
hi(0, "SnacksPickerSelected", { fg = "#e82ac1" })
hi(0, "SnacksProfilerBadgeInfo", { bg = "#212b33", fg = "#00c4e1" })
hi(0, "SnacksProfilerBadgeTrace", { bg = "#202122", fg = "#47589e" })
hi(0, "SnacksProfilerIconInfo", { bg = "#294c59", fg = "#00c4e1" })
hi(0, "SnacksProfilerIconTrace", { bg = "#282a2e", fg = "#47589e" })
hi(0, "SnacksScratchDesc", { link = "SnacksProfilerBadgeInfo" })
hi(0, "SnacksScratchKey", { link = "SnacksProfilerIconInfo" })
hi(0, "SnacksZenIcon", { fg = "#9876f3" })
hi(0, "Special", { fg = "#00c4e1" })
hi(0, "SpecialKey", { fg = "#47589e" })
hi(0, "SpellBad", { sp = "#ca4d9d", undercurl = true })
hi(0, "SpellCap", { sp = "#d1b765", undercurl = true })
hi(0, "SpellLocal", { sp = "#0cb9d7", undercurl = true })
hi(0, "SpellRare", { sp = "#12bc9e", undercurl = true })
hi(0, "Statement", { fg = "#b597ff" })
hi(0, "StatusLine", { bg = "#171717", fg = "#a1b0e7" })
hi(0, "StatusLineNC", { bg = "#171717", fg = "#303e7a" })
hi(0, "String", { fg = "#86d551" })
hi(0, "Substitute", { bg = "#dc83bd", fg = "#121429" })
hi(0, "TabLine", { bg = "#171717", fg = "#303e7a" })
hi(0, "TabLineFill", { bg = "#171717" })
hi(0, "TabLineSel", { bg = "#7fa4e8", fg = "#121429" })
hi(0, "Title", { bold = true, fg = "#6ba1ff" })
hi(0, "Todo", { bg = "#cbb87c", fg = "#161a32" })
hi(0, "TodoBgFIX", { bg = "#be5d98", bold = true, fg = "#000000" })
hi(0, "TodoBgHACK", { bg = "#cbb87c", bold = true, fg = "#000000" })
hi(0, "TodoBgNOTE", { bg = "#44b89f", bold = true, fg = "#000000" })
hi(0, "TodoBgPERF", { bg = "#b1a0ed", bold = true, fg = "#000000" })
hi(0, "TodoBgTEST", { bg = "#b1a0ed", bold = true, fg = "#000000" })
hi(0, "TodoBgTODO", { bg = "#44b7d0", bold = true, fg = "#000000" })
hi(0, "TodoBgWARN", { bg = "#cbb87c", bold = true, fg = "#000000" })
hi(0, "TodoFgFIX", { fg = "#db30a4" })
hi(0, "TodoFgHACK", { fg = "#d9b53e" })
hi(0, "TodoFgNOTE", { fg = "#00bd9e" })
hi(0, "TodoFgPERF", { fg = "#b597ff" })
hi(0, "TodoFgTEST", { fg = "#b597ff" })
hi(0, "TodoFgTODO", { fg = "#00b9d8" })
hi(0, "TodoFgWARN", { fg = "#d9b53e" })
hi(0, "TodoSignFIX", { fg = "#db30a4" })
hi(0, "TodoSignHACK", { fg = "#d9b53e" })
hi(0, "TodoSignNOTE", { fg = "#00bd9e" })
hi(0, "TodoSignPERF", { fg = "#b597ff" })
hi(0, "TodoSignTEST", { fg = "#b597ff" })
hi(0, "TodoSignTODO", { fg = "#00b9d8" })
hi(0, "TodoSignWARN", { fg = "#d9b53e" })
hi(0, "TroubleCount", { bg = "#41444d", fg = "#b597ff" })
hi(0, "TroubleNormal", { fg = "#bacaff" })
hi(0, "TroubleText", { fg = "#a1b0e7" })
hi(0, "Type", { fg = "#00c4e1" })
hi(0, "VertSplit", { fg = "#121429" })
hi(0, "Visual", { bg = "#2e3646" })
hi(0, "VisualNOS", { bg = "#2e3646" })
hi(0, "WarningMsg", { fg = "#d9b53e" })
hi(0, "WhichKey", { fg = "#79cffe" })
hi(0, "WhichKeyDesc", { fg = "#b597ff" })
hi(0, "WhichKeyGroup", { fg = "#6ba1ff" })
hi(0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
hi(0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
hi(0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
hi(0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
hi(0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
hi(0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
hi(0, "WhichKeyIconRed", { link = "MiniIconsRed" })
hi(0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
hi(0, "WhichKeySeparator", { fg = "#485aa8" })
hi(0, "WhichKeyValue", { fg = "#6877bd" })
hi(0, "Whitespace", { fg = "#303e7a" })
hi(0, "WildMenu", { bg = "#2e3646" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#7b78c4" })
hi(0, "YankyPut", { link = "Search" })
hi(0, "YankyYanked", { link = "IncSearch" })
hi(0, "debugBreakpoint", { bg = "#1e2a34", fg = "#00b9d8" })
hi(0, "diffAdded", { fg = "#13a0b2" })
hi(0, "diffChanged", { fg = "#4a82d4" })
hi(0, "diffFile", { fg = "#6ba1ff" })
hi(0, "diffIndexLine", { fg = "#b597ff" })
hi(0, "diffLine", { fg = "#485aa8" })
hi(0, "diffNewFile", { fg = "#e8ac3b" })
hi(0, "diffOldFile", { fg = "#d9b53e" })
hi(0, "diffRemoved", { fg = "#954078" })
hi(0, "dosIniLabel", { link = "@property" })
hi(0, "healthError", { fg = "#db30a4" })
hi(0, "healthSuccess", { fg = "#46e0ce" })
hi(0, "healthWarning", { fg = "#d9b53e" })
hi(0, "helpCommand", { bg = "#474a53", fg = "#6ba1ff" })
hi(0, "helpExample", { fg = "#485aa8" })
hi(0, "htmlH1", { bold = true, fg = "#b597ff" })
hi(0, "htmlH2", { bold = true, fg = "#6ba1ff" })
hi(0, "lCursor", { bg = "#c1ccec", fg = "#161a32" })
hi(0, "lualine_a_command", { bg = "#cbb87c", fg = "#121429" })
hi(0, "lualine_a_inactive", { bg = "#171717", fg = "#6ba1ff" })
hi(0, "lualine_a_insert", { bg = "#9ecc85", fg = "#121429" })
hi(0, "lualine_a_normal", { bg = "#7fa4e8", fg = "#121429" })
hi(0, "lualine_a_replace", { bg = "#dc83bd", fg = "#121429" })
hi(0, "lualine_a_terminal", { bg = "#8ad6ca", fg = "#121429" })
hi(0, "lualine_a_visual", { bg = "#b1a0ed", fg = "#121429" })
hi(0, "lualine_b_command", { bg = "#41444d", fg = "#d9b53e" })
hi(0, "lualine_b_inactive", { bg = "#171717", bold = true, fg = "#303e7a" })
hi(0, "lualine_b_insert", { bg = "#41444d", fg = "#86d551" })
hi(0, "lualine_b_normal", { bg = "#41444d", fg = "#6ba1ff" })
hi(0, "lualine_b_replace", { bg = "#41444d", fg = "#ec6bc4" })
hi(0, "lualine_b_terminal", { bg = "#41444d", fg = "#46e0ce" })
hi(0, "lualine_b_visual", { bg = "#41444d", fg = "#b597ff" })
hi(0, "lualine_c_5_command", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_c_5_inactive", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_c_5_insert", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_c_5_normal", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_c_5_replace", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_c_5_terminal", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_c_5_visual", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_c_8_LV_Bold_command", { bg = "#171717", bold = true, fg = "#bacaff" })
hi(0, "lualine_c_8_LV_Bold_inactive", { bg = "#171717", bold = true, fg = "#bacaff" })
hi(0, "lualine_c_8_LV_Bold_insert", { bg = "#171717", bold = true, fg = "#bacaff" })
hi(0, "lualine_c_8_LV_Bold_normal", { bg = "#171717", bold = true, fg = "#bacaff" })
hi(0, "lualine_c_8_LV_Bold_replace", { bg = "#171717", bold = true, fg = "#bacaff" })
hi(0, "lualine_c_8_LV_Bold_terminal", { bg = "#171717", bold = true, fg = "#bacaff" })
hi(0, "lualine_c_8_LV_Bold_visual", { bg = "#171717", bold = true, fg = "#bacaff" })
hi(0, "lualine_c_diagnostics_error_command", { bg = "#171717", fg = "#db30a4" })
hi(0, "lualine_c_diagnostics_error_inactive", { bg = "#171717", fg = "#db30a4" })
hi(0, "lualine_c_diagnostics_error_insert", { bg = "#171717", fg = "#db30a4" })
hi(0, "lualine_c_diagnostics_error_normal", { bg = "#171717", fg = "#db30a4" })
hi(0, "lualine_c_diagnostics_error_replace", { bg = "#171717", fg = "#db30a4" })
hi(0, "lualine_c_diagnostics_error_terminal", { bg = "#171717", fg = "#db30a4" })
hi(0, "lualine_c_diagnostics_error_visual", { bg = "#171717", fg = "#db30a4" })
hi(0, "lualine_c_diagnostics_hint_command", { bg = "#171717", fg = "#00bd9e" })
hi(0, "lualine_c_diagnostics_hint_inactive", { bg = "#171717", fg = "#00bd9e" })
hi(0, "lualine_c_diagnostics_hint_insert", { bg = "#171717", fg = "#00bd9e" })
hi(0, "lualine_c_diagnostics_hint_normal", { bg = "#171717", fg = "#00bd9e" })
hi(0, "lualine_c_diagnostics_hint_replace", { bg = "#171717", fg = "#00bd9e" })
hi(0, "lualine_c_diagnostics_hint_terminal", { bg = "#171717", fg = "#00bd9e" })
hi(0, "lualine_c_diagnostics_hint_visual", { bg = "#171717", fg = "#00bd9e" })
hi(0, "lualine_c_diagnostics_info_command", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_diagnostics_info_inactive", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_diagnostics_info_insert", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_diagnostics_info_normal", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_diagnostics_info_replace", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_diagnostics_info_terminal", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_diagnostics_info_visual", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_diagnostics_warn_command", { bg = "#171717", fg = "#d9b53e" })
hi(0, "lualine_c_diagnostics_warn_inactive", { bg = "#171717", fg = "#d9b53e" })
hi(0, "lualine_c_diagnostics_warn_insert", { bg = "#171717", fg = "#d9b53e" })
hi(0, "lualine_c_diagnostics_warn_normal", { bg = "#171717", fg = "#d9b53e" })
hi(0, "lualine_c_diagnostics_warn_replace", { bg = "#171717", fg = "#d9b53e" })
hi(0, "lualine_c_diagnostics_warn_terminal", { bg = "#171717", fg = "#d9b53e" })
hi(0, "lualine_c_diagnostics_warn_visual", { bg = "#171717", fg = "#d9b53e" })
hi(0, "lualine_c_filetype_MiniIconsAzure_command", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_filetype_MiniIconsAzure_inactive", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_filetype_MiniIconsAzure_insert", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_filetype_MiniIconsAzure_normal", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_filetype_MiniIconsAzure_replace", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_filetype_MiniIconsAzure_terminal", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_filetype_MiniIconsAzure_visual", { bg = "#171717", fg = "#00b9d8" })
hi(0, "lualine_c_inactive", { bg = "#171717", fg = "#303e7a" })
hi(0, "lualine_c_normal", { bg = "#171717", fg = "#a1b0e7" })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#41444d", fg = "#d9b53e" })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#41444d", fg = "#6ba1ff" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_filetype_MiniIconsAzure_command", { bg = "#171717", fg = "#303e7a" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_x_11_command", { bg = "#171717", fg = "#303e7a" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_filetype_MiniIconsAzure_normal", { bg = "#171717", fg = "#303e7a" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#171717", fg = "#303e7a" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_11_normal", { bg = "#171717", fg = "#303e7a" })
hi(0, "lualine_x_10", { link = "DiagnosticError" })
hi(0, "lualine_x_11_command", { bg = "#171717", fg = "#b597ff" })
hi(0, "lualine_x_11_inactive", { bg = "#171717", fg = "#b597ff" })
hi(0, "lualine_x_11_insert", { bg = "#171717", fg = "#b597ff" })
hi(0, "lualine_x_11_normal", { bg = "#171717", fg = "#b597ff" })
hi(0, "lualine_x_11_replace", { bg = "#171717", fg = "#b597ff" })
hi(0, "lualine_x_11_terminal", { bg = "#171717", fg = "#b597ff" })
hi(0, "lualine_x_11_visual", { bg = "#171717", fg = "#b597ff" })
hi(0, "lualine_x_12_command", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_12_inactive", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_12_insert", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_12_normal", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_12_replace", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_12_terminal", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_12_visual", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_13_command", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_13_inactive", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_13_insert", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_13_normal", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_13_replace", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_13_terminal", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_13_visual", { bg = "#171717", fg = "#e8ac3b" })
hi(0, "lualine_x_14_command", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_x_14_inactive", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_x_14_insert", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_x_14_normal", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_x_14_replace", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_x_14_terminal", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_x_14_visual", { bg = "#171717", fg = "#00c4e1" })
hi(0, "lualine_x_diff_added_command", { bg = "#171717", fg = "#13a0b2" })
hi(0, "lualine_x_diff_added_inactive", { bg = "#171717", fg = "#13a0b2" })
hi(0, "lualine_x_diff_added_insert", { bg = "#171717", fg = "#13a0b2" })
hi(0, "lualine_x_diff_added_normal", { bg = "#171717", fg = "#13a0b2" })
hi(0, "lualine_x_diff_added_replace", { bg = "#171717", fg = "#13a0b2" })
hi(0, "lualine_x_diff_added_terminal", { bg = "#171717", fg = "#13a0b2" })
hi(0, "lualine_x_diff_added_visual", { bg = "#171717", fg = "#13a0b2" })
hi(0, "lualine_x_diff_modified_command", { bg = "#171717", fg = "#4a82d4" })
hi(0, "lualine_x_diff_modified_inactive", { bg = "#171717", fg = "#4a82d4" })
hi(0, "lualine_x_diff_modified_insert", { bg = "#171717", fg = "#4a82d4" })
hi(0, "lualine_x_diff_modified_normal", { bg = "#171717", fg = "#4a82d4" })
hi(0, "lualine_x_diff_modified_replace", { bg = "#171717", fg = "#4a82d4" })
hi(0, "lualine_x_diff_modified_terminal", { bg = "#171717", fg = "#4a82d4" })
hi(0, "lualine_x_diff_modified_visual", { bg = "#171717", fg = "#4a82d4" })
hi(0, "lualine_x_diff_removed_command", { bg = "#171717", fg = "#954078" })
hi(0, "lualine_x_diff_removed_inactive", { bg = "#171717", fg = "#954078" })
hi(0, "lualine_x_diff_removed_insert", { bg = "#171717", fg = "#954078" })
hi(0, "lualine_x_diff_removed_normal", { bg = "#171717", fg = "#954078" })
hi(0, "lualine_x_diff_removed_replace", { bg = "#171717", fg = "#954078" })
hi(0, "lualine_x_diff_removed_terminal", { bg = "#171717", fg = "#954078" })
hi(0, "lualine_x_diff_removed_visual", { bg = "#171717", fg = "#954078" })
hi(0, "qfFileName", { fg = "#6ba1ff" })
hi(0, "qfLineNr", { fg = "#6877bd" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#15161e"
g.terminal_color_1 = "#e67ac2"
g.terminal_color_2 = "#95d072"
g.terminal_color_3 = "#d1b765"
g.terminal_color_4 = "#75a3f7"
g.terminal_color_5 = "#b39dfb"
g.terminal_color_6 = "#7ccffe"
g.terminal_color_7 = "#a7b2d6"
g.terminal_color_8 = "#3f4968"
g.terminal_color_9 = "#ef8ccd"
g.terminal_color_10 = "#90e354"
g.terminal_color_11 = "#e7c447"
g.terminal_color_12 = "#89b1ff"
g.terminal_color_13 = "#bfacff"
g.terminal_color_14 = "#a3daff"
g.terminal_color_15 = "#becbf5"
