-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
  vim.cmd("highlight clear")
end
vim.g.colors_name = "tokyonight-night-blu"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { link = "PreProc" })
hi(0, "@attribute", { link = "PreProc" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.printf", { link = "SpecialChar" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { fg = "#009d5b" })
hi(0, "@comment.hint", { fg = "#e57d96" })
hi(0, "@comment.info", { fg = "#ce89d1" })
hi(0, "@comment.note", { fg = "#e57d96" })
hi(0, "@comment.todo", { fg = "#8e9cf6" })
hi(0, "@comment.warning", { fg = "#c3bc69" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Define" })
hi(0, "@constructor", { fg = "#52b8fb" })
hi(0, "@constructor.tsx", { fg = "#d992d8" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "@function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "@function.method" })
hi(0, "@keyword", { fg = "#2c9adc", italic = true })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { link = "Debug" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.function", { fg = "#52b8fb" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { link = "@operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { link = "@keyword" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label", { fg = "#8e9cf6" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.deriveHelper", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.formatSpecifier", { link = "@markup.list" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.generic", { link = "@variable" })
hi(0, "@lsp.type.interface", { fg = "#d49ee0" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { sp = "#009d5b", undercurl = true })
hi(0, "@lsp.type.variable", vim.empty_dict())
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.type.defaultLibrary", { fg = "#b279b4" })
hi(0, "@lsp.typemod.typeAlias.defaultLibrary", { fg = "#b279b4" })
hi(0, "@lsp.typemod.variable.callable", { link = "@function" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "@constant" })
hi(0, "@markup", { link = "@none" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "Type" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#161c26", fg = "#161c26", nocombine = true, sp = "#b9ccf5", underdouble = true })
hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#8e9cf6" })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#161c26", fg = "#161c26", nocombine = true, sp = "#b9ccf5", underline = true })
hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#c3bc69" })
hi(0, "@markup.heading.3.markdown", { bold = true, fg = "#ffa066" })
hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#e57d96" })
hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#52b8fb" })
hi(0, "@markup.heading.6.markdown", { bold = true, fg = "#2c9adc" })
hi(0, "@markup.heading.7.markdown", { bold = true, fg = "#9dcb68" })
hi(0, "@markup.heading.8.markdown", { bold = true, fg = "#00c297" })
hi(0, "@markup.link", { fg = "#e57d96" })
hi(0, "@markup.link.label", { link = "SpecialChar" })
hi(0, "@markup.link.label.symbol", { link = "Identifier" })
hi(0, "@markup.link.url", { link = "Underlined" })
hi(0, "@markup.list", { fg = "#e7befb" })
hi(0, "@markup.list.checked", { fg = "#faaac5" })
hi(0, "@markup.list.markdown", { bold = true, fg = "#9dcb68" })
hi(0, "@markup.list.unchecked", { fg = "#8e9cf6" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@markup.raw.markdown_inline", { bg = "#3c4a68", fg = "#8e9cf6" })
hi(0, "@module", { link = "Directory" })
hi(0, "@module.builtin", { fg = "#00c297" })
hi(0, "@namespace.builtin", { link = "@variable.builtin" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { fg = "#e7befb" })
hi(0, "@property", { fg = "#faaac5" })
hi(0, "@punctuation.bracket", { fg = "#a2b3d6" })
hi(0, "@punctuation.delimiter", { fg = "#e7befb" })
hi(0, "@punctuation.special", { fg = "#e7befb" })
hi(0, "@punctuation.special.markdown", { fg = "#9dcb68" })
hi(0, "@string.documentation", { fg = "#c3bc69" })
hi(0, "@string.escape", { fg = "#52b8fb" })
hi(0, "@string.regexp", { fg = "#ffdcf2" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@tag", { link = "Label" })
hi(0, "@tag.attribute", { link = "@property" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@tag.delimiter.tsx", { fg = "#6b76b7" })
hi(0, "@tag.javascript", { fg = "#00c297" })
hi(0, "@tag.tsx", { fg = "#00c297" })
hi(0, "@type.builtin", { fg = "#b279b4" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "@keyword" })
hi(0, "@variable", { fg = "#b9ccf5" })
hi(0, "@variable.builtin", { fg = "#00c297" })
hi(0, "@variable.member", { fg = "#faaac5" })
hi(0, "@variable.parameter", { fg = "#c3bc69" })
hi(0, "@variable.parameter.builtin", { fg = "#c0bf85" })
hi(0, "Added", { ctermfg = 10, fg = "#ffd5cc" })
hi(0, "BlinkCmpCursorLineMenuHack", { bg = "#303b55" })
hi(0, "BlinkCmpDoc", { bg = "#12171e", fg = "#b9ccf5" })
hi(0, "BlinkCmpDocBorder", { bg = "#12171e", fg = "#b279b4" })
hi(0, "BlinkCmpGhostText", { fg = "#3c4a68" })
hi(0, "BlinkCmpKindArray", { link = "LspKindArray" })
hi(0, "BlinkCmpKindBoolean", { link = "LspKindBoolean" })
hi(0, "BlinkCmpKindClass", { link = "LspKindClass" })
hi(0, "BlinkCmpKindCodeium", { fg = "#e57d96" })
hi(0, "BlinkCmpKindColor", { link = "LspKindColor" })
hi(0, "BlinkCmpKindConstant", { link = "LspKindConstant" })
hi(0, "BlinkCmpKindConstructor", { link = "LspKindConstructor" })
hi(0, "BlinkCmpKindCopilot", { fg = "#e57d96" })
hi(0, "BlinkCmpKindDefault", { fg = "#a2b3d6" })
hi(0, "BlinkCmpKindEnum", { link = "LspKindEnum" })
hi(0, "BlinkCmpKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "BlinkCmpKindEvent", { link = "LspKindEvent" })
hi(0, "BlinkCmpKindField", { link = "LspKindField" })
hi(0, "BlinkCmpKindFile", { link = "LspKindFile" })
hi(0, "BlinkCmpKindFolder", { link = "LspKindFolder" })
hi(0, "BlinkCmpKindFunction", { link = "LspKindFunction" })
hi(0, "BlinkCmpKindInterface", { link = "LspKindInterface" })
hi(0, "BlinkCmpKindKey", { link = "LspKindKey" })
hi(0, "BlinkCmpKindKeyword", { link = "LspKindKeyword" })
hi(0, "BlinkCmpKindMethod", { link = "LspKindMethod" })
hi(0, "BlinkCmpKindModule", { link = "LspKindModule" })
hi(0, "BlinkCmpKindNamespace", { link = "LspKindNamespace" })
hi(0, "BlinkCmpKindNull", { link = "LspKindNull" })
hi(0, "BlinkCmpKindNumber", { link = "LspKindNumber" })
hi(0, "BlinkCmpKindObject", { link = "LspKindObject" })
hi(0, "BlinkCmpKindOperator", { link = "LspKindOperator" })
hi(0, "BlinkCmpKindPackage", { link = "LspKindPackage" })
hi(0, "BlinkCmpKindProperty", { link = "LspKindProperty" })
hi(0, "BlinkCmpKindReference", { link = "LspKindReference" })
hi(0, "BlinkCmpKindSnippet", { link = "LspKindSnippet" })
hi(0, "BlinkCmpKindString", { link = "LspKindString" })
hi(0, "BlinkCmpKindStruct", { link = "LspKindStruct" })
hi(0, "BlinkCmpKindSupermaven", { fg = "#e57d96" })
hi(0, "BlinkCmpKindTabNine", { fg = "#e57d96" })
hi(0, "BlinkCmpKindText", { link = "LspKindText" })
hi(0, "BlinkCmpKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "BlinkCmpKindUnit", { link = "LspKindUnit" })
hi(0, "BlinkCmpKindValue", { link = "LspKindValue" })
hi(0, "BlinkCmpKindVariable", { link = "LspKindVariable" })
hi(0, "BlinkCmpLabel", { fg = "#b9ccf5" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#374361", strikethrough = true })
hi(0, "BlinkCmpLabelMatch", { fg = "#d992d8" })
hi(0, "BlinkCmpMenu", { bg = "#12171e", fg = "#b9ccf5" })
hi(0, "BlinkCmpMenuBorder", { bg = "#12171e", fg = "#b279b4" })
hi(0, "BlinkCmpSignatureHelp", { bg = "#12171e", fg = "#b9ccf5" })
hi(0, "BlinkCmpSignatureHelpBorder", { bg = "#12171e", fg = "#b279b4" })
hi(0, "Bold", { bold = true, fg = "#b9ccf5" })
hi(0, "BufferLineBackground", { bg = "#11151c", fg = "#4f6189" })
hi(0, "BufferLineBuffer", { bg = "#11151c", fg = "#4f6189" })
hi(0, "BufferLineBufferSelected", { bg = "#161c26", bold = true, fg = "#b9ccf5", italic = true })
hi(0, "BufferLineBufferVisible", { bg = "#141922", fg = "#4f6189" })
hi(0, "BufferLineCloseButton", { bg = "#11151c", fg = "#4f6189" })
hi(0, "BufferLineCloseButtonSelected", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "BufferLineCloseButtonVisible", { bg = "#141922", fg = "#4f6189" })
hi(0, "BufferLineDiagnostic", { bg = "#11151c", fg = "#3c4866" })
hi(0, "BufferLineDiagnosticSelected", { bg = "#161c26", bold = true, fg = "#8a99b7", italic = true })
hi(0, "BufferLineDiagnosticVisible", { bg = "#141922", fg = "#3c4866" })
hi(0, "BufferLineDuplicate", { bg = "#11151c", fg = "#4b5c82", italic = true })
hi(0, "BufferLineDuplicateSelected", { bg = "#161c26", fg = "#4b5c82", italic = true })
hi(0, "BufferLineDuplicateVisible", { bg = "#141922", fg = "#4b5c82", italic = true })
hi(0, "BufferLineError", { bg = "#11151c", fg = "#4f6189", sp = "#009d5b" })
hi(0, "BufferLineErrorDiagnostic", { bg = "#11151c", fg = "#3c4866", sp = "#017644" })
hi(0, "BufferLineErrorDiagnosticSelected", { bg = "#161c26", bold = true, fg = "#017644", italic = true, sp = "#017644" })
hi(0, "BufferLineErrorDiagnosticVisible", { bg = "#141922", fg = "#3c4866" })
hi(0, "BufferLineErrorSelected", { bg = "#161c26", bold = true, fg = "#009d5b", italic = true, sp = "#009d5b" })
hi(0, "BufferLineErrorVisible", { bg = "#141922", fg = "#4f6189" })
hi(0, "BufferLineFill", { bg = "#0b0f14", fg = "#4f6189" })
hi(0, "BufferLineGroupLabel", { bg = "#4f6189", fg = "#0b0f14" })
hi(0, "BufferLineGroupSeparator", { bg = "#0b0f14", fg = "#4f6189" })
hi(0, "BufferLineHint", { bg = "#11151c", fg = "#4f6189", sp = "#e57d96" })
hi(0, "BufferLineHintDiagnostic", { bg = "#11151c", fg = "#3c4866", sp = "#ac5d70" })
hi(0, "BufferLineHintDiagnosticSelected", { bg = "#161c26", bold = true, fg = "#ac5d70", italic = true, sp = "#ac5d70" })
hi(0, "BufferLineHintDiagnosticVisible", { bg = "#141922", fg = "#3c4866" })
hi(0, "BufferLineHintSelected", { bg = "#161c26", bold = true, fg = "#e57d96", italic = true, sp = "#e57d96" })
hi(0, "BufferLineHintVisible", { bg = "#141922", fg = "#4f6189" })
hi(0, "BufferLineIndicatorSelected", { fg = "#777cba" })
hi(0, "BufferLineIndicatorVisible", { bg = "#141922", fg = "#141922" })
hi(0, "BufferLineInfo", { bg = "#11151c", fg = "#4f6189", sp = "#ce89d1" })
hi(0, "BufferLineInfoDiagnostic", { bg = "#11151c", fg = "#3c4866", sp = "#9a669d" })
hi(0, "BufferLineInfoDiagnosticSelected", { bg = "#161c26", bold = true, fg = "#9a669d", italic = true, sp = "#9a669d" })
hi(0, "BufferLineInfoDiagnosticVisible", { bg = "#141922", fg = "#3c4866" })
hi(0, "BufferLineInfoSelected", { bg = "#161c26", bold = true, fg = "#ce89d1", italic = true, sp = "#ce89d1" })
hi(0, "BufferLineInfoVisible", { bg = "#141922", fg = "#4f6189" })
hi(0, "BufferLineMiniIconsAzure", { bg = "#11151c", fg = "#ce89d1" })
hi(0, "BufferLineMiniIconsAzureInactive", { bg = "#141922", fg = "#ce89d1" })
hi(0, "BufferLineMiniIconsAzureSelected", { bg = "#161c26", fg = "#ce89d1" })
hi(0, "BufferLineMiniIconsGreyInactive", { bg = "#141922", fg = "#b9ccf5" })
hi(0, "BufferLineMiniIconsGreySelected", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "BufferLineMiniIconsOrange", { bg = "#11151c", fg = "#9dcb68" })
hi(0, "BufferLineMiniIconsOrangeInactive", { bg = "#141922", fg = "#9dcb68" })
hi(0, "BufferLineMiniIconsOrangeSelected", { bg = "#161c26", fg = "#9dcb68" })
hi(0, "BufferLineMiniIconsYellow", { bg = "#11151c", fg = "#c3bc69" })
hi(0, "BufferLineMiniIconsYellowInactive", { bg = "#141922", fg = "#c3bc69" })
hi(0, "BufferLineMiniIconsYellowSelected", { bg = "#161c26", fg = "#c3bc69" })
hi(0, "BufferLineModified", { bg = "#11151c", fg = "#ffa066" })
hi(0, "BufferLineModifiedSelected", { bg = "#161c26", fg = "#ffa066" })
hi(0, "BufferLineModifiedVisible", { bg = "#141922", fg = "#ffa066" })
hi(0, "BufferLineNumbers", { bg = "#11151c", fg = "#4f6189" })
hi(0, "BufferLineNumbersSelected", { bg = "#161c26", bold = true, fg = "#b9ccf5", italic = true })
hi(0, "BufferLineNumbersVisible", { bg = "#141922", fg = "#4f6189" })
hi(0, "BufferLineOffsetSeparator", { bg = "#0b0f14", fg = "#6486a9" })
hi(0, "BufferLinePick", { bg = "#11151c", bold = true, fg = "#009d5b", italic = true })
hi(0, "BufferLinePickSelected", { bg = "#161c26", bold = true, fg = "#009d5b", italic = true })
hi(0, "BufferLinePickVisible", { bg = "#141922", bold = true, fg = "#009d5b", italic = true })
hi(0, "BufferLineSeparator", { bg = "#11151c", fg = "#0b0f14" })
hi(0, "BufferLineSeparatorSelected", { bg = "#161c26", fg = "#0b0f14" })
hi(0, "BufferLineSeparatorVisible", { bg = "#141922", fg = "#0b0f14" })
hi(0, "BufferLineTab", { bg = "#11151c", fg = "#4f6189" })
hi(0, "BufferLineTabClose", { bg = "#11151c", fg = "#4f6189" })
hi(0, "BufferLineTabSelected", { bg = "#161c26", fg = "#8e9cf6" })
hi(0, "BufferLineTabSeparator", { bg = "#11151c", fg = "#0b0f14" })
hi(0, "BufferLineTabSeparatorSelected", { bg = "#161c26", fg = "#0b0f14" })
hi(0, "BufferLineTruncMarker", { bg = "#0b0f14", fg = "#4f6189" })
hi(0, "BufferLineWarning", { bg = "#11151c", fg = "#4f6189", sp = "#c3bc69" })
hi(0, "BufferLineWarningDiagnostic", { bg = "#11151c", fg = "#3c4866", sp = "#928d4f" })
hi(0, "BufferLineWarningDiagnosticSelected", { bg = "#161c26", bold = true, fg = "#928d4f", italic = true, sp = "#928d4f" })
hi(0, "BufferLineWarningDiagnosticVisible", { bg = "#141922", fg = "#3c4866" })
hi(0, "BufferLineWarningSelected", { bg = "#161c26", bold = true, fg = "#c3bc69", italic = true, sp = "#c3bc69" })
hi(0, "BufferLineWarningVisible", { bg = "#141922", fg = "#4f6189" })
hi(0, "Changed", { ctermfg = 14, fg = "#ffd0ee" })
hi(0, "Character", { fg = "#ffa066" })
hi(0, "ColorColumn", { bg = "#13171e" })
hi(0, "Comment", { fg = "#4f6189", italic = true })
hi(0, "Conceal", { fg = "#6a7da2" })
hi(0, "Constant", { fg = "#9dcb68" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#b9ccf5", fg = "#161c26" })
hi(0, "CursorColumn", { bg = "#272f42" })
hi(0, "CursorIM", { bg = "#b9ccf5", fg = "#161c26" })
hi(0, "CursorLine", { bg = "#272f42" })
hi(0, "CursorLineNr", { bold = true, fg = "#9dcb68" })
hi(0, "Debug", { fg = "#9dcb68" })
hi(0, "Delimiter", { link = "Special" })
hi(0, "DiagnosticDeprecated", { sp = "#ade1bc", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#009d5b" })
hi(0, "DiagnosticHint", { fg = "#e57d96" })
hi(0, "DiagnosticInfo", { fg = "#ce89d1" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#ffd5cc" })
hi(0, "DiagnosticUnderlineError", { sp = "#009d5b", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#e57d96", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#ce89d1", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#ffd5cc", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#c3bc69", undercurl = true })
hi(0, "DiagnosticUnnecessary", { fg = "#3c4a68" })
hi(0, "DiagnosticVirtualTextError", { bg = "#14292b", fg = "#009d5b" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#2d2431", fg = "#e57d96" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#2b2537", fg = "#ce89d1" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#272d2d", fg = "#c3bc69" })
hi(0, "DiagnosticWarn", { fg = "#c3bc69" })
hi(0, "DiffAdd", { bg = "#302b3a" })
hi(0, "DiffChange", { bg = "#1c2331" })
hi(0, "DiffDelete", { bg = "#112f2d" })
hi(0, "DiffText", { bg = "#424870" })
hi(0, "Directory", { fg = "#8e9cf6" })
hi(0, "EndOfBuffer", { fg = "#161c26" })
hi(0, "Error", { fg = "#009d5b" })
hi(0, "ErrorMsg", { fg = "#009d5b" })
hi(0, "FlashBackdrop", { fg = "#4f5e7e" })
hi(0, "FlashLabel", { bg = "#00a58b", bold = true, fg = "#b9ccf5" })
hi(0, "FloatBorder", { bg = "#12171e", fg = "#b279b4" })
hi(0, "FloatShadow", { bg = "#505258", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#505258", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#12171e", fg = "#b279b4" })
hi(0, "FoldColumn", { bg = "#161c26", fg = "#4f6189" })
hi(0, "Folded", { bg = "#374361", fg = "#8e9cf6" })
hi(0, "Foo", { bg = "#00a58b", fg = "#b9ccf5" })
hi(0, "Function", { fg = "#8e9cf6" })
hi(0, "FzfLuaBackdrop", { bg = "#000000" })
hi(0, "FzfLuaBorder", { bg = "#12171e", fg = "#b279b4" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#ffcff8" })
hi(0, "FzfLuaBufFlagCur", { fg = "#00af5f" })
hi(0, "FzfLuaBufNr", { fg = "#f4f0cd" })
hi(0, "FzfLuaCursor", { link = "IncSearch" })
hi(0, "FzfLuaDirPart", { fg = "#a2b3d6" })
hi(0, "FzfLuaFilePart", { link = "FzfLuaFzfNormal" })
hi(0, "FzfLuaFzfCursorLine", { link = "Visual" })
hi(0, "FzfLuaFzfNormal", { fg = "#b9ccf5" })
hi(0, "FzfLuaFzfPointer", { fg = "#00a58b" })
hi(0, "FzfLuaFzfSeparator", { bg = "#12171e", fg = "#9dcb68" })
hi(0, "FzfLuaHeaderBind", { link = "@punctuation.special" })
hi(0, "FzfLuaHeaderText", { link = "Title" })
hi(0, "FzfLuaLivePrompt", { fg = "#00ccb3" })
hi(0, "FzfLuaLiveSym", { fg = "#00ccb3" })
hi(0, "FzfLuaNormal", { bg = "#12171e", fg = "#b9ccf5" })
hi(0, "FzfLuaPath", { link = "Directory" })
hi(0, "FzfLuaPathColNr", { fg = "#ffcff8" })
hi(0, "FzfLuaPathLineNr", { fg = "#ffbfab" })
hi(0, "FzfLuaPreviewTitle", { bg = "#12171e", fg = "#b279b4" })
hi(0, "FzfLuaScrollBorderBackCompat", { bg = "#b279b4", fg = "#12171e" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#f4f0cd" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#e5d0fd" })
hi(0, "FzfLuaTitle", { bg = "#12171e", fg = "#9dcb68" })
hi(0, "GitSignsAdd", { fg = "#ad7ba7" })
hi(0, "GitSignsChange", { fg = "#777cba" })
hi(0, "GitSignsDelete", { fg = "#1d7458" })
hi(0, "GitSignsStagedAdd", { fg = "#563d53" })
hi(0, "GitSignsStagedAddCul", { fg = "#563d53" })
hi(0, "GitSignsStagedAddLn", { bg = "#302b3a" })
hi(0, "GitSignsStagedAddNr", { fg = "#563d53" })
hi(0, "GitSignsStagedChange", { fg = "#3b3e5d" })
hi(0, "GitSignsStagedChangeCul", { fg = "#3b3e5d" })
hi(0, "GitSignsStagedChangeLn", { bg = "#1c2331" })
hi(0, "GitSignsStagedChangeNr", { fg = "#3b3e5d" })
hi(0, "GitSignsStagedChangedelete", { fg = "#3b3e5d" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#3b3e5d" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#1c2331" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#3b3e5d" })
hi(0, "GitSignsStagedDelete", { fg = "#123a2c" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#123a2c" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#123a2c" })
hi(0, "GitSignsStagedTopdelete", { fg = "#123a2c" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#123a2c" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#123a2c" })
hi(0, "GitSignsStagedUntracked", { fg = "#563d53" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#563d53" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#302b3a" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#563d53" })
hi(0, "GrugFarHelpHeader", { fg = "#4f6189" })
hi(0, "GrugFarHelpHeaderKey", { fg = "#d3b3fc" })
hi(0, "GrugFarInputLabel", { fg = "#d992d8" })
hi(0, "GrugFarInputPlaceholder", { fg = "#4f5e7e" })
hi(0, "GrugFarResultsChangeIndicator", { fg = "#777cba" })
hi(0, "GrugFarResultsHeader", { fg = "#9dcb68" })
hi(0, "GrugFarResultsLineColumn", { fg = "#4f5e7e" })
hi(0, "GrugFarResultsLineNo", { fg = "#4f5e7e" })
hi(0, "GrugFarResultsMatch", { bg = "#00c297", fg = "#13171e" })
hi(0, "GrugFarResultsStats", { fg = "#8e9cf6" })
hi(0, "Identifier", { fg = "#52b8fb" })
hi(0, "IncSearch", { bg = "#9dcb68", fg = "#13171e" })
hi(0, "Italic", { fg = "#b9ccf5", italic = true })
hi(0, "Keyword", { fg = "#d3b3fc", italic = true })
hi(0, "LazyBackdrop", { bg = "#000000" })
hi(0, "LazyBold", { bold = true })
hi(0, "LazyItalic", { italic = true })
hi(0, "LazyProgressDone", { bold = true, fg = "#00a58b" })
hi(0, "LazyProgressTodo", { bold = true, fg = "#374361" })
hi(0, "LineNr", { fg = "#374361" })
hi(0, "LineNrAbove", { fg = "#374361" })
hi(0, "LineNrBelow", { fg = "#374361" })
hi(0, "LspCodeLens", { fg = "#4f6189" })
hi(0, "LspInfoBorder", { bg = "#12171e", fg = "#b279b4" })
hi(0, "LspInlayHint", { bg = "#1b212d", fg = "#4f5e7e" })
hi(0, "LspKindArray", { link = "@punctuation.bracket" })
hi(0, "LspKindBoolean", { link = "@boolean" })
hi(0, "LspKindClass", { link = "@type" })
hi(0, "LspKindColor", { link = "Special" })
hi(0, "LspKindConstant", { link = "@constant" })
hi(0, "LspKindConstructor", { link = "@constructor" })
hi(0, "LspKindEnum", { link = "@lsp.type.enum" })
hi(0, "LspKindEnumMember", { link = "@lsp.type.enumMember" })
hi(0, "LspKindEvent", { link = "Special" })
hi(0, "LspKindField", { link = "@variable.member" })
hi(0, "LspKindFile", { link = "Normal" })
hi(0, "LspKindFolder", { link = "Directory" })
hi(0, "LspKindFunction", { link = "@function" })
hi(0, "LspKindInterface", { link = "@lsp.type.interface" })
hi(0, "LspKindKey", { link = "@variable.member" })
hi(0, "LspKindKeyword", { link = "@lsp.type.keyword" })
hi(0, "LspKindMethod", { link = "@function.method" })
hi(0, "LspKindModule", { link = "@module" })
hi(0, "LspKindNamespace", { link = "@module" })
hi(0, "LspKindNull", { link = "@constant.builtin" })
hi(0, "LspKindNumber", { link = "@number" })
hi(0, "LspKindObject", { link = "@constant" })
hi(0, "LspKindOperator", { link = "@operator" })
hi(0, "LspKindPackage", { link = "@module" })
hi(0, "LspKindProperty", { link = "@property" })
hi(0, "LspKindReference", { link = "@markup.link" })
hi(0, "LspKindSnippet", { link = "Conceal" })
hi(0, "LspKindString", { link = "@string" })
hi(0, "LspKindStruct", { link = "@lsp.type.struct" })
hi(0, "LspKindText", { link = "@markup" })
hi(0, "LspKindTypeParameter", { link = "@lsp.type.typeParameter" })
hi(0, "LspKindUnit", { link = "@lsp.type.struct" })
hi(0, "LspKindValue", { link = "@string" })
hi(0, "LspKindVariable", { link = "@variable" })
hi(0, "LspReferenceRead", { bg = "#374361" })
hi(0, "LspReferenceText", { bg = "#374361" })
hi(0, "LspReferenceWrite", { bg = "#374361" })
hi(0, "LspSignatureActiveParameter", { bg = "#1e263a", bold = true })
hi(0, "MatchParen", { bold = true, fg = "#9dcb68" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#b9ccf5" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bg = "#12171e", bold = true, fg = "#b279b4" })
hi(0, "MiniHipatternsFixme", { bg = "#009d5b", bold = true, fg = "#13171e" })
hi(0, "MiniHipatternsHack", { bg = "#c3bc69", bold = true, fg = "#13171e" })
hi(0, "MiniHipatternsNote", { bg = "#e57d96", bold = true, fg = "#13171e" })
hi(0, "MiniHipatternsTodo", { bg = "#ce89d1", bold = true, fg = "#13171e" })
hi(0, "MiniIconsAzure", { fg = "#ce89d1" })
hi(0, "MiniIconsBlue", { fg = "#8e9cf6" })
hi(0, "MiniIconsCyan", { fg = "#e57d96" })
hi(0, "MiniIconsGreen", { fg = "#ffa066" })
hi(0, "MiniIconsGrey", { fg = "#b9ccf5" })
hi(0, "MiniIconsOrange", { fg = "#9dcb68" })
hi(0, "MiniIconsPurple", { fg = "#2c9adc" })
hi(0, "MiniIconsRed", { fg = "#00c297" })
hi(0, "MiniIconsYellow", { fg = "#c3bc69" })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#c3bc69", italic = true })
hi(0, "MiniStarterHeader", { fg = "#8e9cf6" })
hi(0, "MiniStarterInactive", { fg = "#4f6189", italic = true })
hi(0, "MiniStarterItem", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "MiniStarterItemBullet", { fg = "#b279b4" })
hi(0, "MiniStarterItemPrefix", { fg = "#c3bc69" })
hi(0, "MiniStarterQuery", { fg = "#ce89d1" })
hi(0, "MiniStarterSection", { fg = "#d992d8" })
hi(0, "MiniSurround", { bg = "#9dcb68", fg = "#13171e" })
hi(0, "ModeMsg", { bold = true, fg = "#a2b3d6" })
hi(0, "MoreMsg", { fg = "#8e9cf6" })
hi(0, "MsgArea", { fg = "#a2b3d6" })
hi(0, "NoiceCmdlineIconInput", { fg = "#c3bc69" })
hi(0, "NoiceCmdlineIconLua", { fg = "#d992d8" })
hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#c3bc69" })
hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#d992d8" })
hi(0, "NoiceCmdlinePopupTitleInput", { fg = "#c3bc69" })
hi(0, "NoiceCmdlinePopupTitleLua", { fg = "#d992d8" })
hi(0, "NoiceCompletionItemKindArray", { link = "LspKindArray" })
hi(0, "NoiceCompletionItemKindBoolean", { link = "LspKindBoolean" })
hi(0, "NoiceCompletionItemKindClass", { link = "LspKindClass" })
hi(0, "NoiceCompletionItemKindColor", { link = "LspKindColor" })
hi(0, "NoiceCompletionItemKindConstant", { link = "LspKindConstant" })
hi(0, "NoiceCompletionItemKindConstructor", { link = "LspKindConstructor" })
hi(0, "NoiceCompletionItemKindDefault", { fg = "#a2b3d6" })
hi(0, "NoiceCompletionItemKindEnum", { link = "LspKindEnum" })
hi(0, "NoiceCompletionItemKindEnumMember", { link = "LspKindEnumMember" })
hi(0, "NoiceCompletionItemKindEvent", { link = "LspKindEvent" })
hi(0, "NoiceCompletionItemKindField", { link = "LspKindField" })
hi(0, "NoiceCompletionItemKindFile", { link = "LspKindFile" })
hi(0, "NoiceCompletionItemKindFolder", { link = "LspKindFolder" })
hi(0, "NoiceCompletionItemKindFunction", { link = "LspKindFunction" })
hi(0, "NoiceCompletionItemKindInterface", { link = "LspKindInterface" })
hi(0, "NoiceCompletionItemKindKey", { link = "LspKindKey" })
hi(0, "NoiceCompletionItemKindKeyword", { link = "LspKindKeyword" })
hi(0, "NoiceCompletionItemKindMethod", { link = "LspKindMethod" })
hi(0, "NoiceCompletionItemKindModule", { link = "LspKindModule" })
hi(0, "NoiceCompletionItemKindNamespace", { link = "LspKindNamespace" })
hi(0, "NoiceCompletionItemKindNull", { link = "LspKindNull" })
hi(0, "NoiceCompletionItemKindNumber", { link = "LspKindNumber" })
hi(0, "NoiceCompletionItemKindObject", { link = "LspKindObject" })
hi(0, "NoiceCompletionItemKindOperator", { link = "LspKindOperator" })
hi(0, "NoiceCompletionItemKindPackage", { link = "LspKindPackage" })
hi(0, "NoiceCompletionItemKindProperty", { link = "LspKindProperty" })
hi(0, "NoiceCompletionItemKindReference", { link = "LspKindReference" })
hi(0, "NoiceCompletionItemKindSnippet", { link = "LspKindSnippet" })
hi(0, "NoiceCompletionItemKindString", { link = "LspKindString" })
hi(0, "NoiceCompletionItemKindStruct", { link = "LspKindStruct" })
hi(0, "NoiceCompletionItemKindText", { link = "LspKindText" })
hi(0, "NoiceCompletionItemKindTypeParameter", { link = "LspKindTypeParameter" })
hi(0, "NoiceCompletionItemKindUnit", { link = "LspKindUnit" })
hi(0, "NoiceCompletionItemKindValue", { link = "LspKindValue" })
hi(0, "NoiceCompletionItemKindVariable", { link = "LspKindVariable" })
hi(0, "NoiceFormatProgressDone", { bg = "#4956a1", fg = "#b9ccf5" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#4f5e7e" })
hi(0, "Normal", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "NormalFloat", { bg = "#12171e", fg = "#b9ccf5" })
hi(0, "NormalNC", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "NormalSB", { bg = "#12171e", fg = "#a2b3d6" })
hi(0, "NvimInternalError", { bg = "#00a44d", ctermbg = 9, ctermfg = 9, fg = "#00a44d" })
hi(0, "Operator", { fg = "#e7befb" })
hi(0, "Pmenu", { bg = "#12171e", fg = "#b9ccf5" })
hi(0, "PmenuMatch", { bg = "#12171e", fg = "#d992d8" })
hi(0, "PmenuMatchSel", { bg = "#303b55", fg = "#d992d8" })
hi(0, "PmenuSbar", { bg = "#1a2129" })
hi(0, "PmenuSel", { bg = "#303b55" })
hi(0, "PmenuThumb", { bg = "#374361" })
hi(0, "PreProc", { fg = "#d3b3fc" })
hi(0, "Question", { fg = "#8e9cf6" })
hi(0, "QuickFixLine", { bg = "#2a3357", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#8e9cf6" })
hi(0, "RainbowDelimiterCyan", { fg = "#d3b3fc" })
hi(0, "RainbowDelimiterGreen", { fg = "#ffa066" })
hi(0, "RainbowDelimiterOrange", { fg = "#9dcb68" })
hi(0, "RainbowDelimiterRed", { fg = "#00c297" })
hi(0, "RainbowDelimiterViolet", { fg = "#2c9adc" })
hi(0, "RainbowDelimiterYellow", { fg = "#c3bc69" })
hi(0, "RedrawDebugClear", { bg = "#6a5400", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#75291f", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#00361b", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 9, fg = "#ade1bc" })
hi(0, "RenderMarkdownBullet", { fg = "#9dcb68" })
hi(0, "RenderMarkdownCode", { bg = "#12171e" })
hi(0, "RenderMarkdownCodeInline", { link = "@markup.raw.markdown_inline" })
hi(0, "RenderMarkdownDash", { fg = "#9dcb68" })
hi(0, "RenderMarkdownH1Bg", { bg = "#23293b" })
hi(0, "RenderMarkdownH1Fg", { bold = true, fg = "#8e9cf6" })
hi(0, "RenderMarkdownH2Bg", { bg = "#272d2d" })
hi(0, "RenderMarkdownH2Fg", { bold = true, fg = "#c3bc69" })
hi(0, "RenderMarkdownH3Bg", { bg = "#2f2a2d" })
hi(0, "RenderMarkdownH3Fg", { bold = true, fg = "#ffa066" })
hi(0, "RenderMarkdownH4Bg", { bg = "#2d2431" })
hi(0, "RenderMarkdownH4Fg", { bold = true, fg = "#e57d96" })
hi(0, "RenderMarkdownH5Bg", { bg = "#1e2c3b" })
hi(0, "RenderMarkdownH5Fg", { bold = true, fg = "#52b8fb" })
hi(0, "RenderMarkdownH6Bg", { bg = "#1b2938" })
hi(0, "RenderMarkdownH6Fg", { bold = true, fg = "#2c9adc" })
hi(0, "RenderMarkdownH7Bg", { bg = "#232d2d" })
hi(0, "RenderMarkdownH7Fg", { bold = true, fg = "#9dcb68" })
hi(0, "RenderMarkdownH8Bg", { bg = "#182c31" })
hi(0, "RenderMarkdownH8Fg", { bold = true, fg = "#00c297" })
hi(0, "RenderMarkdownTableHead", { fg = "#00c297" })
hi(0, "RenderMarkdownTableRow", { fg = "#9dcb68" })
hi(0, "Search", { bg = "#4956a1", fg = "#b9ccf5" })
hi(0, "SignColumn", { bg = "#161c26", fg = "#374361" })
hi(0, "SignColumnSB", { bg = "#12171e", fg = "#374361" })
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksDashboardDesc", { fg = "#d3b3fc" })
hi(0, "SnacksDashboardDir", { fg = "#4f5e7e" })
hi(0, "SnacksDashboardFooter", { fg = "#d992d8" })
hi(0, "SnacksDashboardHeader", { fg = "#8e9cf6" })
hi(0, "SnacksDashboardIcon", { fg = "#d992d8" })
hi(0, "SnacksDashboardKey", { fg = "#9dcb68" })
hi(0, "SnacksDashboardSpecial", { fg = "#2c9adc" })
hi(0, "SnacksIndent", { fg = "#374361", nocombine = true })
hi(0, "SnacksIndent1", { fg = "#8e9cf6", nocombine = true })
hi(0, "SnacksIndent2", { fg = "#c3bc69", nocombine = true })
hi(0, "SnacksIndent3", { fg = "#ffa066", nocombine = true })
hi(0, "SnacksIndent4", { fg = "#e57d96", nocombine = true })
hi(0, "SnacksIndent5", { fg = "#52b8fb", nocombine = true })
hi(0, "SnacksIndent6", { fg = "#2c9adc", nocombine = true })
hi(0, "SnacksIndent7", { fg = "#9dcb68", nocombine = true })
hi(0, "SnacksIndent8", { fg = "#00c297", nocombine = true })
hi(0, "SnacksIndentScope", { fg = "#d992d8", nocombine = true })
hi(0, "SnacksInputBorder", { fg = "#c3bc69" })
hi(0, "SnacksInputIcon", { fg = "#d992d8" })
hi(0, "SnacksInputTitle", { fg = "#c3bc69" })
hi(0, "SnacksNotifierBorderDebug", { bg = "#161c26", fg = "#2c384e" })
hi(0, "SnacksNotifierBorderError", { bg = "#161c26", fg = "#005038" })
hi(0, "SnacksNotifierBorderInfo", { bg = "#161c26", fg = "#62446a" })
hi(0, "SnacksNotifierBorderTrace", { bg = "#161c26", fg = "#244e6f" })
hi(0, "SnacksNotifierBorderWarn", { bg = "#161c26", fg = "#5b5c41" })
hi(0, "SnacksNotifierDebug", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "SnacksNotifierError", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "SnacksNotifierIconDebug", { fg = "#4f6189" })
hi(0, "SnacksNotifierIconError", { fg = "#009d5b" })
hi(0, "SnacksNotifierIconInfo", { fg = "#ce89d1" })
hi(0, "SnacksNotifierIconTrace", { fg = "#2c9adc" })
hi(0, "SnacksNotifierIconWarn", { fg = "#c3bc69" })
hi(0, "SnacksNotifierInfo", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "SnacksNotifierTitleDebug", { fg = "#4f6189" })
hi(0, "SnacksNotifierTitleError", { fg = "#009d5b" })
hi(0, "SnacksNotifierTitleInfo", { fg = "#ce89d1" })
hi(0, "SnacksNotifierTitleTrace", { fg = "#2c9adc" })
hi(0, "SnacksNotifierTitleWarn", { fg = "#c3bc69" })
hi(0, "SnacksNotifierTrace", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "SnacksNotifierWarn", { bg = "#161c26", fg = "#b9ccf5" })
hi(0, "SnacksPickerBoxTitle", { bg = "#12171e", fg = "#9dcb68" })
hi(0, "SnacksPickerInputBorder", { bg = "#12171e", fg = "#9dcb68" })
hi(0, "SnacksPickerInputTitle", { bg = "#12171e", fg = "#9dcb68" })
hi(0, "SnacksPickerPickWin", { bg = "#4956a1", bold = true, fg = "#b9ccf5" })
hi(0, "SnacksPickerPickWinCurrent", { bg = "#00a58b", bold = true, fg = "#b9ccf5" })
hi(0, "SnacksPickerSelected", { fg = "#00a58b" })
hi(0, "SnacksPickerToggle", { link = "SnacksProfilerBadgeInfo" })
hi(0, "SnacksProfilerBadgeInfo", { bg = "#2c2737", fg = "#d992d8" })
hi(0, "SnacksProfilerBadgeTrace", { bg = "#1b212d", fg = "#4f5e7e" })
hi(0, "SnacksProfilerIconInfo", { bg = "#523d5b", fg = "#d992d8" })
hi(0, "SnacksProfilerIconTrace", { bg = "#23293c", fg = "#4f5e7e" })
hi(0, "SnacksScratchDesc", { link = "SnacksProfilerBadgeInfo" })
hi(0, "SnacksScratchKey", { link = "SnacksProfilerIconInfo" })
hi(0, "SnacksZenIcon", { fg = "#2c9adc" })
hi(0, "Special", { fg = "#d992d8" })
hi(0, "SpecialKey", { fg = "#4f5e7e" })
hi(0, "SpellBad", { sp = "#009d5b", undercurl = true })
hi(0, "SpellCap", { sp = "#c3bc69", undercurl = true })
hi(0, "SpellLocal", { sp = "#ce89d1", undercurl = true })
hi(0, "SpellRare", { sp = "#e57d96", undercurl = true })
hi(0, "Statement", { fg = "#52b8fb" })
hi(0, "StatusLine", { bg = "#12171e", fg = "#a2b3d6" })
hi(0, "StatusLineNC", { bg = "#12171e", fg = "#374361" })
hi(0, "String", { fg = "#ffa066" })
hi(0, "Substitute", { bg = "#00c297", fg = "#13171e" })
hi(0, "TabLine", { bg = "#12171e", fg = "#374361" })
hi(0, "TabLineFill", { bg = "#13171e" })
hi(0, "TabLineSel", { bg = "#8e9cf6", fg = "#13171e" })
hi(0, "Title", { bold = true, fg = "#8e9cf6" })
hi(0, "Todo", { bg = "#c3bc69", fg = "#161c26" })
hi(0, "TodoBgFIX", { bg = "#009d5b", bold = true, fg = "#161c26" })
hi(0, "TodoBgHACK", { bg = "#c3bc69", bold = true, fg = "#161c26" })
hi(0, "TodoBgNOTE", { bg = "#e57d96", bold = true, fg = "#161c26" })
hi(0, "TodoBgPERF", { bg = "#52b8fb", bold = true, fg = "#161c26" })
hi(0, "TodoBgTEST", { bg = "#52b8fb", bold = true, fg = "#161c26" })
hi(0, "TodoBgTODO", { bg = "#ce89d1", bold = true, fg = "#161c26" })
hi(0, "TodoBgWARN", { bg = "#c3bc69", bold = true, fg = "#161c26" })
hi(0, "TodoFgFIX", { fg = "#009d5b" })
hi(0, "TodoFgHACK", { fg = "#c3bc69" })
hi(0, "TodoFgNOTE", { fg = "#e57d96" })
hi(0, "TodoFgPERF", { fg = "#52b8fb" })
hi(0, "TodoFgTEST", { fg = "#52b8fb" })
hi(0, "TodoFgTODO", { fg = "#ce89d1" })
hi(0, "TodoFgWARN", { fg = "#c3bc69" })
hi(0, "TodoSignFIX", { bg = "#161c26", fg = "#009d5b" })
hi(0, "TodoSignHACK", { bg = "#161c26", fg = "#c3bc69" })
hi(0, "TodoSignNOTE", { bg = "#161c26", fg = "#e57d96" })
hi(0, "TodoSignPERF", { bg = "#161c26", fg = "#52b8fb" })
hi(0, "TodoSignTEST", { bg = "#161c26", fg = "#52b8fb" })
hi(0, "TodoSignTODO", { bg = "#161c26", fg = "#ce89d1" })
hi(0, "TodoSignWARN", { bg = "#161c26", fg = "#c3bc69" })
hi(0, "TroubleCount", { bg = "#374361", fg = "#52b8fb" })
hi(0, "TroubleNormal", { bg = "#12171e", fg = "#b9ccf5" })
hi(0, "TroubleStatusline0", { bg = "#12171e", fg = "#ffa066" })
hi(0, "TroubleStatusline1", { bg = "#12171e", fg = "#b9ccf5" })
hi(0, "TroubleStatusline2", { bg = "#12171e", fg = "#8e9cf6" })
hi(0, "TroubleText", { fg = "#a2b3d6" })
hi(0, "Type", { fg = "#d992d8" })
hi(0, "VertSplit", { fg = "#13171e" })
hi(0, "Visual", { bg = "#2a3357" })
hi(0, "VisualNOS", { bg = "#2a3357" })
hi(0, "WarningMsg", { fg = "#c3bc69" })
hi(0, "WhichKey", { fg = "#d3b3fc" })
hi(0, "WhichKeyDesc", { fg = "#52b8fb" })
hi(0, "WhichKeyGroup", { fg = "#8e9cf6" })
hi(0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
hi(0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
hi(0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
hi(0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
hi(0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
hi(0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
hi(0, "WhichKeyIconRed", { link = "MiniIconsRed" })
hi(0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
hi(0, "WhichKeyNormal", { bg = "#12171e" })
hi(0, "WhichKeySeparator", { fg = "#4f6189" })
hi(0, "WhichKeyValue", { fg = "#6a7da2" })
hi(0, "Whitespace", { fg = "#374361" })
hi(0, "WildMenu", { bg = "#2a3357" })
hi(0, "WinBar", { link = "StatusLine" })
hi(0, "WinBarNC", { link = "StatusLineNC" })
hi(0, "WinSeparator", { fg = "#6486a9" })
hi(0, "YankyPut", { link = "Search" })
hi(0, "YankyYanked", { link = "IncSearch" })
hi(0, "debugBreakpoint", { bg = "#2b2537", fg = "#ce89d1" })
hi(0, "debugPC", { bg = "#12171e" })
hi(0, "diffAdded", { bg = "#302b3a", fg = "#ad7ba7" })
hi(0, "diffChanged", { bg = "#1c2331", fg = "#777cba" })
hi(0, "diffFile", { fg = "#8e9cf6" })
hi(0, "diffIndexLine", { fg = "#52b8fb" })
hi(0, "diffLine", { fg = "#4f6189" })
hi(0, "diffNewFile", { bg = "#302b3a", fg = "#d992d8" })
hi(0, "diffOldFile", { bg = "#112f2d", fg = "#d992d8" })
hi(0, "diffRemoved", { bg = "#112f2d", fg = "#1d7458" })
hi(0, "dosIniLabel", { link = "@property" })
hi(0, "healthError", { fg = "#009d5b" })
hi(0, "healthSuccess", { fg = "#faaac5" })
hi(0, "healthWarning", { fg = "#c3bc69" })
hi(0, "helpCommand", { bg = "#3c4a68", fg = "#8e9cf6" })
hi(0, "helpExample", { fg = "#4f6189" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlBoldItalic", { bold = true, italic = true })
hi(0, "htmlBoldUnderline", { bold = true, underline = true })
hi(0, "htmlBoldUnderlineItalic", { bold = true, italic = true, underline = true })
hi(0, "htmlH1", { bold = true, fg = "#52b8fb" })
hi(0, "htmlH2", { bold = true, fg = "#8e9cf6" })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlStrike", { strikethrough = true })
hi(0, "htmlUnderline", { underline = true })
hi(0, "htmlUnderlineItalic", { italic = true, underline = true })
hi(0, "lCursor", { bg = "#b9ccf5", fg = "#161c26" })
hi(0, "lualine_a_command", { bg = "#c3bc69", fg = "#13171e", nocombine = true })
hi(0, "lualine_a_inactive", { bg = "#12171e", fg = "#8e9cf6", nocombine = true })
hi(0, "lualine_a_insert", { bg = "#ffa066", fg = "#13171e", nocombine = true })
hi(0, "lualine_a_normal", { bg = "#8e9cf6", fg = "#13171e", nocombine = true })
hi(0, "lualine_a_replace", { bg = "#00c297", fg = "#13171e", nocombine = true })
hi(0, "lualine_a_terminal", { bg = "#faaac5", fg = "#13171e", nocombine = true })
hi(0, "lualine_a_visual", { bg = "#52b8fb", fg = "#13171e", nocombine = true })
hi(0, "lualine_b_command", { bg = "#374361", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_b_inactive", { bg = "#12171e", bold = true, fg = "#374361", nocombine = true })
hi(0, "lualine_b_insert", { bg = "#374361", fg = "#ffa066", nocombine = true })
hi(0, "lualine_b_normal", { bg = "#374361", fg = "#8e9cf6", nocombine = true })
hi(0, "lualine_b_replace", { bg = "#374361", fg = "#00c297", nocombine = true })
hi(0, "lualine_b_terminal", { bg = "#374361", fg = "#faaac5", nocombine = true })
hi(0, "lualine_b_visual", { bg = "#374361", fg = "#52b8fb", nocombine = true })
hi(0, "lualine_c_3_command", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_c_3_inactive", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_c_3_insert", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_c_3_normal", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_c_3_replace", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_c_3_terminal", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_c_3_visual", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_c_6_LV_Bold_command", { bg = "#12171e", bold = true, fg = "#b9ccf5", nocombine = true })
hi(0, "lualine_c_6_LV_Bold_inactive", { bg = "#12171e", bold = true, fg = "#b9ccf5", nocombine = true })
hi(0, "lualine_c_6_LV_Bold_insert", { bg = "#12171e", bold = true, fg = "#b9ccf5", nocombine = true })
hi(0, "lualine_c_6_LV_Bold_normal", { bg = "#12171e", bold = true, fg = "#b9ccf5", nocombine = true })
hi(0, "lualine_c_6_LV_Bold_replace", { bg = "#12171e", bold = true, fg = "#b9ccf5", nocombine = true })
hi(0, "lualine_c_6_LV_Bold_terminal", { bg = "#12171e", bold = true, fg = "#b9ccf5", nocombine = true })
hi(0, "lualine_c_6_LV_Bold_visual", { bg = "#12171e", bold = true, fg = "#b9ccf5", nocombine = true })
hi(0, "lualine_c_6_LV_MatchParen_command", { bg = "#12171e", bold = true, fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_6_LV_MatchParen_inactive", { bg = "#12171e", bold = true, fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_6_LV_MatchParen_insert", { bg = "#12171e", bold = true, fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_6_LV_MatchParen_normal", { bg = "#12171e", bold = true, fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_6_LV_MatchParen_replace", { bg = "#12171e", bold = true, fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_6_LV_MatchParen_terminal", { bg = "#12171e", bold = true, fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_6_LV_MatchParen_visual", { bg = "#12171e", bold = true, fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_diagnostics_error_command", { bg = "#12171e", fg = "#009d5b", nocombine = true })
hi(0, "lualine_c_diagnostics_error_inactive", { bg = "#12171e", fg = "#009d5b", nocombine = true })
hi(0, "lualine_c_diagnostics_error_insert", { bg = "#12171e", fg = "#009d5b", nocombine = true })
hi(0, "lualine_c_diagnostics_error_normal", { bg = "#12171e", fg = "#009d5b", nocombine = true })
hi(0, "lualine_c_diagnostics_error_replace", { bg = "#12171e", fg = "#009d5b", nocombine = true })
hi(0, "lualine_c_diagnostics_error_terminal", { bg = "#12171e", fg = "#009d5b", nocombine = true })
hi(0, "lualine_c_diagnostics_error_visual", { bg = "#12171e", fg = "#009d5b", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_command", { bg = "#12171e", fg = "#e57d96", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_inactive", { bg = "#12171e", fg = "#e57d96", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_insert", { bg = "#12171e", fg = "#e57d96", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_normal", { bg = "#12171e", fg = "#e57d96", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_replace", { bg = "#12171e", fg = "#e57d96", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_terminal", { bg = "#12171e", fg = "#e57d96", nocombine = true })
hi(0, "lualine_c_diagnostics_hint_visual", { bg = "#12171e", fg = "#e57d96", nocombine = true })
hi(0, "lualine_c_diagnostics_info_command", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_diagnostics_info_inactive", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_diagnostics_info_insert", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_diagnostics_info_normal", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_diagnostics_info_replace", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_diagnostics_info_terminal", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_diagnostics_info_visual", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_command", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_inactive", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_insert", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_normal", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_replace", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_terminal", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_diagnostics_warn_visual", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_command", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_inactive", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_insert", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_normal", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_replace", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_terminal", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsAzure_visual", { bg = "#12171e", fg = "#ce89d1", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsOrange_command", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsOrange_inactive", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsOrange_insert", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsOrange_normal", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsOrange_replace", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsOrange_terminal", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsOrange_visual", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsYellow_command", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsYellow_inactive", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsYellow_insert", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsYellow_normal", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsYellow_replace", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsYellow_terminal", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_filetype_MiniIconsYellow_visual", { bg = "#12171e", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_c_inactive", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_c_normal", { bg = "#12171e", fg = "#a2b3d6", nocombine = true })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = "#374361", fg = "#c3bc69", nocombine = true })
hi(0, "lualine_transitional_lualine_a_insert_to_lualine_b_insert", { bg = "#374361", fg = "#ffa066", nocombine = true })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = "#374361", fg = "#8e9cf6", nocombine = true })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_c_filetype_MiniIconsYellow_normal", { bg = "#12171e", fg = "#8e9cf6", nocombine = true })
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_c_normal", { bg = "#12171e", fg = "#8e9cf6", nocombine = true })
hi(0, "lualine_transitional_lualine_a_terminal_to_lualine_b_terminal", { bg = "#374361", fg = "#faaac5", nocombine = true })
hi(0, "lualine_transitional_lualine_a_terminal_to_lualine_c_normal", { bg = "#12171e", fg = "#faaac5", nocombine = true })
hi(0, "lualine_transitional_lualine_a_visual_to_lualine_b_visual", { bg = "#374361", fg = "#52b8fb", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_3_command", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_filetype_MiniIconsAzure_command", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_filetype_MiniIconsOrange_command", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_filetype_MiniIconsYellow_command", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_x_12_command", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_x_9_command", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_x_diff_removed_command", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_c_3_insert", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_c_filetype_MiniIconsAzure_insert", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_c_filetype_MiniIconsOrange_insert", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_x_12_insert", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_x_9_insert", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_x_diff_added_insert", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_x_diff_modified_insert", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_3_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_diagnostics_warn_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_filetype_MiniIconsAzure_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_filetype_MiniIconsOrange_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_filetype_MiniIconsYellow_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_12_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_9_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_diff_added_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_diff_modified_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_x_diff_removed_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_terminal_to_lualine_c_3_terminal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_terminal_to_lualine_c_filetype_MiniIconsAzure_terminal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_terminal_to_lualine_c_filetype_MiniIconsOrange_terminal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_terminal_to_lualine_c_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_terminal_to_lualine_x_12_terminal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_terminal_to_lualine_x_9_terminal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_terminal_to_lualine_x_diff_removed_terminal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_visual_to_lualine_c_filetype_MiniIconsAzure_visual", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_visual_to_lualine_c_normal", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_visual_to_lualine_x_12_visual", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_transitional_lualine_b_visual_to_lualine_x_diff_removed_visual", { bg = "#12171e", fg = "#374361", nocombine = true })
hi(0, "lualine_x_10_command", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_10_inactive", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_10_insert", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_10_normal", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_10_replace", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_10_terminal", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_10_visual", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_11_command", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_11_inactive", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_11_insert", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_11_normal", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_11_replace", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_11_terminal", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_11_visual", { bg = "#12171e", fg = "#9dcb68", nocombine = true })
hi(0, "lualine_x_12_command", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_x_12_inactive", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_x_12_insert", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_x_12_normal", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_x_12_replace", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_x_12_terminal", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_x_12_visual", { bg = "#12171e", fg = "#d992d8", nocombine = true })
hi(0, "lualine_x_8", { link = "DiagnosticError" })
hi(0, "lualine_x_9_command", { bg = "#12171e", fg = "#52b8fb", nocombine = true })
hi(0, "lualine_x_9_inactive", { bg = "#12171e", fg = "#52b8fb", nocombine = true })
hi(0, "lualine_x_9_insert", { bg = "#12171e", fg = "#52b8fb", nocombine = true })
hi(0, "lualine_x_9_normal", { bg = "#12171e", fg = "#52b8fb", nocombine = true })
hi(0, "lualine_x_9_replace", { bg = "#12171e", fg = "#52b8fb", nocombine = true })
hi(0, "lualine_x_9_terminal", { bg = "#12171e", fg = "#52b8fb", nocombine = true })
hi(0, "lualine_x_9_visual", { bg = "#12171e", fg = "#52b8fb", nocombine = true })
hi(0, "lualine_x_diff_added_command", { bg = "#12171e", fg = "#ad7ba7", nocombine = true })
hi(0, "lualine_x_diff_added_inactive", { bg = "#12171e", fg = "#ad7ba7", nocombine = true })
hi(0, "lualine_x_diff_added_insert", { bg = "#12171e", fg = "#ad7ba7", nocombine = true })
hi(0, "lualine_x_diff_added_normal", { bg = "#12171e", fg = "#ad7ba7", nocombine = true })
hi(0, "lualine_x_diff_added_replace", { bg = "#12171e", fg = "#ad7ba7", nocombine = true })
hi(0, "lualine_x_diff_added_terminal", { bg = "#12171e", fg = "#ad7ba7", nocombine = true })
hi(0, "lualine_x_diff_added_visual", { bg = "#12171e", fg = "#ad7ba7", nocombine = true })
hi(0, "lualine_x_diff_modified_command", { bg = "#12171e", fg = "#777cba", nocombine = true })
hi(0, "lualine_x_diff_modified_inactive", { bg = "#12171e", fg = "#777cba", nocombine = true })
hi(0, "lualine_x_diff_modified_insert", { bg = "#12171e", fg = "#777cba", nocombine = true })
hi(0, "lualine_x_diff_modified_normal", { bg = "#12171e", fg = "#777cba", nocombine = true })
hi(0, "lualine_x_diff_modified_replace", { bg = "#12171e", fg = "#777cba", nocombine = true })
hi(0, "lualine_x_diff_modified_terminal", { bg = "#12171e", fg = "#777cba", nocombine = true })
hi(0, "lualine_x_diff_modified_visual", { bg = "#12171e", fg = "#777cba", nocombine = true })
hi(0, "lualine_x_diff_removed_command", { bg = "#12171e", fg = "#1d7458", nocombine = true })
hi(0, "lualine_x_diff_removed_inactive", { bg = "#12171e", fg = "#1d7458", nocombine = true })
hi(0, "lualine_x_diff_removed_insert", { bg = "#12171e", fg = "#1d7458", nocombine = true })
hi(0, "lualine_x_diff_removed_normal", { bg = "#12171e", fg = "#1d7458", nocombine = true })
hi(0, "lualine_x_diff_removed_replace", { bg = "#12171e", fg = "#1d7458", nocombine = true })
hi(0, "lualine_x_diff_removed_terminal", { bg = "#12171e", fg = "#1d7458", nocombine = true })
hi(0, "lualine_x_diff_removed_visual", { bg = "#12171e", fg = "#1d7458", nocombine = true })
hi(0, "manBold", { bold = true })
hi(0, "manItalic", { italic = true })
hi(0, "manUnderline", { underline = true })
hi(0, "qfFileName", { fg = "#8e9cf6" })
hi(0, "qfLineNr", { fg = "#6a7da2" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#13171e"
g.terminal_color_1 = "#00c297"
g.terminal_color_2 = "#ffa066"
g.terminal_color_3 = "#c3bc69"
g.terminal_color_4 = "#8e9cf6"
g.terminal_color_5 = "#52b8fb"
g.terminal_color_6 = "#d3b3fc"
g.terminal_color_7 = "#a2b3d6"
g.terminal_color_8 = "#3c4a68"
g.terminal_color_9 = "#2acfa4"
g.terminal_color_10 = "#ffb384"
g.terminal_color_11 = "#daca4b"
g.terminal_color_12 = "#9bacfe"
g.terminal_color_13 = "#6ec5ff"
g.terminal_color_14 = "#dbc7fd"
g.terminal_color_15 = "#b9ccf5"
